### ISSUE TITLE
[EKS] [BUG]: eks managed node group nodes won't join cluster if `node-role.kubernetes.io/*` label is set

### ISSUE THREAD

**Issue by 0xDones** [aws/containers-roadmap#2465] opened 2024-11-05 15:57 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
When using ami type `AL2023_ARM_64_STANDARD` on EKS Managed Node groups, if I set the label `node-role.kubernetes.io/my-role = "true"`, the nodes won't join the cluster. Any other label work.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I'd like to be able to specify this label so I can easily see what role my nodes are playing.

**Are you currently working around this issue?**
No

**Additional context**
I'm using the `terraform-aws-eks` module to deploy the cluster and the node groups.

```hcl
      eks_managed_node_group_defaults = {
        ami_type       = "AL2023_ARM_64_STANDARD" # Uses AMI ID 1.30.4-20241024
        instance_types = ["m7g.xlarge"]

        ebs_optimized = true
        metadata_options = {
          http_put_response_hop_limit = 2
        }
      },
      eks_managed_node_groups = {
        simple = {
          min_size     = 1
          max_size     = 10
          desired_size = 1
          labels = {
            # "node-role.kubernetes.io/simple" = "true" # This label prevents nodes from joining the cluster
            "dedicated" = "simple"
          }
        }
      }
...
```

If I add the following arguments to the node group config, which would change the ami type from `AL2023_ARM_64_STANDARD` to `CUSTOM`, then the nodes can join the cluster and are correctly labeled.

```hcl
          enable_bootstrap_user_data = true
          ami_id                     = "ami-01aad0653c8debb9e" # recommended ami for eks v1.30
```

- Adding the tags to the node group after nodes are created will tag the nodes, but new nodes can't join the cluster.
- There are no error messages that indicate the issue and it was very time-consuming to identify the root cause.

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by mikestef9** [comment] 2024-11-05 16:12
Closing as duplicate of #1451

**Closed by mikestef9** 2024-11-05 16:12 UTC
Labels: EKS, Proposed, EKS Managed Nodes, Duplicate / Merged
