### ISSUE TITLE
EKS eu-west-2 London?

### ISSUE THREAD

**Issue by pauldougan** [aws/containers-roadmap#41] opened 2018-12-12 09:33 UTC
no mention of EKS in the London eu-west-2 region, am interested in approximate timelines

**Comment by jsamuel1** [comment] 2018-12-13 03:47
Especially with #brexit uncertainty meaning Ireland workloads may need to move to London if appropriate agreements with EU aren't ratified.

**Comment by Twigiyama** [comment] 2018-12-13 16:51
We would be interested as well.  We have just rolled out our new EKS based platform on AWS Dublin but we would really be interested in having this in AWS London for similar reasons to above.

**Comment by tabern** [comment] 2019-01-16 18:13
Duplicate of #101

**Closed by tabern** 2019-01-16 18:13 UTC
Labels: EKS, Proposed
