### ISSUE TITLE
[EKS] [Support]: Support for EKS 1.28

### ISSUE THREAD

**Issue by amedirr** [aws/containers-roadmap#2101] opened 2023-08-02 18:06 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I'd like EKS support for Kubernetes v1.28.

In preparation for this I'd like to see EKS v1.28 added to the [Amazon EKS Kubernetes release calendar](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar) with a release date initially accurate up-to the quarter.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I'd like to be able to use Kubernetes 1.28 on EKS and be aware of the release timeline to help plan for it.

**Are you currently working around this issue?**
N/A

**Additional context**
[Changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.28.md)
[Major Themes](https://github.com/kubernetes/sig-release/discussions/2271)

**Attachments**
N/A

**Comment by gbarna-bd** [comment] 2023-08-16 09:52
I think this is a duplicate of https://github.com/aws/containers-roadmap/issues/2095.

**Closed** 2023-08-16 18:23 UTC
Labels: Proposed
