### ISSUE TITLE
[EKS] [request]: EKS-optimized Amazon Linux 2 AMI should have aws-ssm-agent installed

### ISSUE THREAD

**Issue by tomaspinho** [aws/containers-roadmap#844] opened 2020-04-20 22:46 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
Install the aws-ssm-agent package on EKS-optimized Amazon Linux 2 AMIs

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Trying to setup SSM sessions with aim to make SSH access redundant on a EKS managed nodes group.

**Are you currently working around this issue?**
Still using SSH.

**Additional context**
NA

**Attachments**
NA

**Comment by millermatt** [comment] 2020-08-14 14:52
Related: https://github.com/aws/containers-roadmap/issues/593

**Comment by mikestef9** [comment] 2020-08-24 03:33
Closing as duplicate of #789

**Closed by mikestef9** 2020-08-24 03:33 UTC
Labels: EKS, Proposed
