### ISSUE TITLE
[service] [request]: Add / Modify EKS subnets

### ISSUE THREAD

**Issue by b52guy** [aws/containers-roadmap#249] opened 2019-04-16 13:49 UTC
**Tell us about your request**
What do you want us to build?  
The ability to modify or add subnet's to existing EKS clusters

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Adding subnets when growing EKS environment size / scale.

**Are you currently working around this issue?**
None

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by whereisaaron** [comment] 2019-05-06 05:26
'[service]' -> '[EKS]'

**Comment by mbarrien** [comment] 2019-08-14 07:05
Duplicate of #170?

**Comment by mikestef9** [comment] 2020-03-27 04:04
Closing as duplicate of #170

**Closed by mikestef9** 2020-03-27 04:04 UTC
Labels: EKS, Proposed
