### ISSUE TITLE
awsvpc Network Mode: Allow ENIs in subnets other than the host

### ISSUE THREAD

**Issue by joelthompson** [aws/containers-roadmap#49] opened 2018-12-12 17:46 UTC
**Tell us about your request**

Currently, per the documentation, when you specify a subnet to run a task on, ECS looks for a host in the subnet you specified. However, AWS allows you to attach an ENI in any subnet to any instance in the same AZ, so you can have instances with ENIs in multiple subnets in the same AZ. This allows you to have different network controls/rules between the "control plane" (the ECS host) and the "data plane" (the ECS task).

One use case is as a workaround for #48 -- this would allow us to put the Fargate hosts in an online subnet but specify tasks in an offline subnet. Another use case is to allow a single ECS host to run multiple tasks that need different network rules, for example one task that needs to talk to the internet and so is in an online subnet and another that must not talk to the internet and so needs to run in an offline subnet.

Additionally, subnet allocation is pretty sticky -- you can't change subnet size without deleting and then recreating the subnet, which requires deleting all resources in the subnet, so it's pretty impactful. Given the issues around #1 and #48, we're currently forced to put all of our resources in internet-facing subnets which requires a larger address space to contain all the resources. We'd like to be able to allocate just the ECS hosts in the online subnet and then place all our resources in the subnet tiers that make the most sense without having to redo all of our network topology once #48 is solved.

**Which service(s) is this request for?**

All services that use the awsvpc network mode :)

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

See above

**Are you currently working around this issue?**

We can sort of work around it with security groups, but those are easier to screw up and accidentally allow an egress rule of 0.0.0.0/0

**Comment by FernandoMiguel** [comment] 2018-12-12 20:06
Multiple ENI on an host halves the total bandwidth per card.
Be extremely careful with that architecture, as I've personally seen organisations that shift and lift to the cloud and tried to keep their same security model and ended up with terrible performance on ec2 hosts from the 3rd ENI attached.

**Comment by copumpkin** [comment] 2018-12-12 20:17
@FernandoMiguel multiple ENIs per host is the whole point of the `awsvpc` networking mode though. I (and I assume other customers) know about the bandwidth splitting, but since it's an AWS-provided/endorsed feature that's deployed and in use all over ECS (including Fargate), it seems worth making that work as nicely as it can.

**Comment by ofiliz** [comment] 2018-12-13 20:43
@joelthompson Re: "per the documentation, when you specify a subnet to run a task on, ECS looks for a host in the subnet you specified" Can you please share a link to that documentation?

The feature you proposed should already work today. The awsvpc task and the instance need not be in the same subnet, just in the same availability zone. You can launch awsvpc tasks to any subnet as long as there is at least one ECS instance in the same availability zone. Just to make sure, I just launched one myself and confirmed that it succeeds.

Could this be some other problem? Maybe misconfiguration in your task definition? I'd love to help.

@FernandoMiguel Re: "Multiple ENI on an host halves the total bandwidth per card"
I'm trying to understand the problem you described. When multiple ENIs are attached to the same EC2 instance, their aggregate network throughput can not exceed the instance's entitled network throughput. However, that does not mean each ENI halves the throughput or the bandwidth is "split". Each ENI can still consume 100% of the instance's entitled throughput. We do not artificially cap per-ENI. Therefore using multiple ENIs should not be any different than a single ENI sending the same amount of traffic. Do you see a different behavior?

**Comment by joelthompson** [comment] 2018-12-13 20:54
Thanks for the response @ofiliz! The documentation is at https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-networking.html -- specifically this bit (emphasis added):

> Then, when you run a task or create a service, specify a network configuration that includes the subnets in which to place your tasks and the security groups to attach to its associated elastic network interface. **The tasks are placed on valid container instances in those subnets**

I hadn't tried this yet, was just reacting to the documentation.

**Comment by ofiliz** [comment] 2018-12-13 20:59
@joelthompson Thanks for the doc link. I agree the language is confusing. It should have said "The tasks are placed on valid container instances in the same availability zones as those subnets". I'll work with the team to correct it. Thanks for reporting!

**Comment by ofiliz** [comment] 2018-12-14 18:46
I'm closing this issue as we already support this functionality, but please let us know if you have any problems or further feedback.

**Closed by ofiliz** 2018-12-14 18:46 UTC
Labels: Proposed
