### ISSUE TITLE
[EKS] [request]: Adjust --event-ttl value

### ISSUE THREAD

**Issue by Hostersi** [aws/containers-roadmap#725] opened 2020-01-27 09:16 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Currently, the default value for **--event-ttl** is 1h, so any describe operation won't show anything under Events section if the latest event happened > 1h ago. We would like to be able to adjust this API Server flag.

**Which service(s) is this request for?**
EKS

**Comment by mikestef9** [comment] 2021-04-26 23:31
Closing as dupe of #785

**Closed by mikestef9** 2021-04-26 23:31 UTC
Labels: EKS, Proposed
