### ISSUE TITLE
[ECR] [request]: Documented SLO/SLA for ECR Replication

### ISSUE THREAD

**Issue by nairb774** [aws/containers-roadmap#1664] opened 2022-02-28 21:56 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

The ECR SLA only covers uptime, but fails to capture other important operational metrics that actually make for a usable service. One such metric would be time to replicate container images from one region to another.

**Which service(s) is this request for?**

ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

We recently setup replication for one of our ECR registries to perform a cross-account, cross region replication. The initial images we observed replicated around 8 seconds after initial publish, which given it needed to replicate something on the order of a GiB, was fairly reasonable if not impressive. With the initial performance seeming to be quite acceptable, we quickly moved on to other things.

The next morning, we started to observe that new images weren't available in the destination as we would expect. Investigating further we noticed that in the source destination the replication status was fully empty. As a result, and with the prior performance, we set about trying to figure out if the testing were due to accidentally getting a configuration right temporarily, and then breaking it shortly after. After running down all the possible cases of mis-configuration, we started to look back through all the prior images to see when it stopped working. We came to find out that image replication, while quick to execute, seems to fall behind. In this instance we were observing the queue(?) about 25 to 30 minutes behind reality.

What sort of expectation should we have with respect to this product? If the delay is going to be as bad as 30 minutes then we might as well disable the replication and just do it ourself. On the other hand, if this was just a temporary outage, and the initial observations are more representative, then we would be fine leaving the replication in place.

Having a documented SLO would, at a minimum, help level set our expectations about where the product is at, and what sort of support AWS is willing to provide for these minor yet important features. Getting the SLO elevated to being part of the ECR SLA would be a great improvement, but we can call that a stretch goal.

For further context on why spelling out an SLO is important, I defer to https://cloud.google.com/blog/products/devops-sre/availability-part-deux-cre-life-lessons and the section "The SLO you run at becomes the SLO everyone expects".

Note: My use of SLO and SLA are most closely aligned with the thinking outlined here: https://cloud.google.com/blog/products/devops-sre/sre-fundamentals-sli-vs-slo-vs-sla

**Are you currently working around this issue?**
How are you currently solving this problem?

Considering implementing our own multi-push/replication implementation rather than using the built in feature. Obviously this would be less than ideal for something that really is just lacking some documentation.

**Additional context**
Anything else we should know?

A related request, but a slightly different take is the request for monitoring of the replication and that can be found at https://github.com/aws/containers-roadmap/issues/1537. While visibility is interesting, without any sort of expectations, it is hard to know how to properly respond to the behavior of the system as a customer.

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by nairb774** [comment] 2022-03-30 22:35
To follow up, we are seeing another outage of the ECR replication service. An image `Pushed at March 30, 2022, 13:53:43 (UTC-07)` is still showing no signs of being replicated at 15:32. The most recently successfully replicated image was initially published at `March 30, 2022, 13:31:47 (UTC-07)` and successfully arrived in the destination at `March 30, 2022, 15:23:13 (UTC-07)` - nearly 2 _hours_ later. Given this typically works in seconds to a minute, it impacts operations when it is falling this far behind.

![image](https://user-images.githubusercontent.com/128795/160941741-48068e06-5aee-42b2-8a66-35ba3caebae8.png)

Worth noting, the AWS status shows everything green for the account:

<img width="787" alt="image" src="https://user-images.githubusercontent.com/128795/160941753-59a42b2c-8542-418c-8a00-34189db46513.png">

Additionally, as usual, the overall status dashboard shows all green:

![image](https://user-images.githubusercontent.com/128795/160941889-d71fd1f2-3291-449e-b2e1-157ddce878e4.png)

**Comment by nairb774** [comment] 2022-03-30 23:44
I was curious to see how often and out of the ordinary this was, so I dumped a bunch of data and put together a record of the experiences we are seeing, and how out of the ordinary this one is.

```bash
#!/bin/bash

REPO="$1"
SRC="$2"
DST="$3"

function dump() {
  TZ=UTC aws ecr --region "$1" describe-images --repository-name "$REPO" \
  | jq -c --arg region "$1" '.imageDetails[] | {imageDigest, pushed: (.imagePushedAt | sub("\\+00:00$"; "Z") | fromdateiso8601), region: $region}'
}

{
  dump "$SRC"
  dump "$DST"
} \
| jq -c -r --slurp --arg src "$SRC" --arg dst "$DST" '
  group_by(.imageDigest)
  | map(
    INDEX(.[]; .region)
    | select(.[$dst])
    | [(.[$src].pushed | todateiso8601), (.[$dst].pushed - .[$src].pushed)]
  )
  | sort_by(.[0])[]
  | @csv
'
```

This is the output of above [us-west-2_to_us-east-1.csv](https://github.com/aws/containers-roadmap/files/8384815/us-west-2_to_us-east-1.csv).

**Comment by bradg-aws** [comment] 2022-04-01 21:50
Hi @nairb774 - Thank you for raising this and providing these details. Could you email us at [smitag AT amazon.com] so that we may investigate this  further?

**Comment by h4xnoodle** [comment] 2022-04-05 18:42
@bradg-aws can you give us some information about where AWS is at with observability around AWS's replication service? It seems pretty clear that your customers need to be able to trust replication and respond to outages appropriately in order to prevent our own deployments from failing, and requiring workarounds.

At this time, it's difficult to use replication as-is since there is no way to tell if it's working correctly, it is also difficult to assess the ability to use replication going forward, as there doesn't seem to be information around expectations your customers can have for your service.

Could you please consider 'influencing' this change?

**Comment by jlbutler** [comment] 2022-04-09 14:03
Apologies for not picking up on this issue earlier, thanks for taking the time to share the situation and data and to others for their input. We’re looking into the backoff characteristics of the service internally, and believe this may be related to the behavior you're observing. We have some near-term work we are doing to evaluate this.
 
This has also brought to our attention that the service documentation doesn’t do a good enough job of setting expectations for customers depending upon replication. We are going to make some changes to more clearly document expected behavior, as a starting point.

We'll update this issue when there is more to share, thanks.

**Comment by arunsollet** [comment] 2022-07-22 20:37
We have updated the ECR documentation to provide general guidance, please refer to:
https://docs.aws.amazon.com/AmazonECR/latest/userguide/replication.html

**Comment by arunsollet** [comment] 2022-07-29 20:02
Thanks for raising the issue, now that documentation has been updated closing the issue.

**Closed by arunsollet** 2022-07-29 20:02 UTC
Labels: ECR, Proposed
