### ISSUE TITLE
[ECS] [Capacity Provider]: Capacity Provider + ASG

### ISSUE THREAD

**Issue by lays147** [aws/containers-roadmap#1086] opened 2020-09-23 15:24 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
- Better error messages when using capacity providers
- Health/Availability of the Capacity Provider when associating a service to it.

Let's imagine that you have the following scenario:
An ECS Cluster with capacity provider configured for FARGATE and a **myapp-capacity-provider** associated with a **myapp-asg** that serves you an EC2 instance with the amazon2 ami optimized for ECS.
Now, we have one ECS service that uses that capacity provider with EC2 to run some tasks.
So far so good.

The launch configuration associated with **myapp-stg** was outdated, so I moved the launch configuration to a launch template and update the ami that the template uses to setup the EC2 and created a new asg named **myapp2-asg**. I have created a new capacity provider and associated the myapp2-asg to it.

Then I updated the myapp-asg to have zero instances running because I wanted to move all the tasks to the newly created capacity provider. 

Everything looked good, but now my service wasn't being able to get a new task up and running... 
![g40](https://user-images.githubusercontent.com/7799231/94031572-62565180-fd95-11ea-89f7-dbbeb378212f.png)

Note some points: 
- There's no info about the container.
- On the services events tab, **no info** like `service myapp-service has started 1 tasks` was shown.
- After a while, the task stopped with the message "Task failed to start".

What I have discovered digging up:
- myapp-service was configured to use the older capacity provider, that was with 0 instances.
- When choosing the capacity provider strategy for the task, no alerts were made by the health(?) of the chosen capacity provider.
- And the error message is shown at the task console, didn't give me any clue that the problem was with the capacity provider associated with the service.
![g66](https://user-images.githubusercontent.com/7799231/94032241-2079db00-fd96-11ea-985d-988f8b5dce7f.png)

**Which service(s) is this request for?**
ECS

**Are you currently working around this issue?**
Correctly configuring the Capacity Provider associated with the ECS Service

**Comment by henriquesantanati** [comment] 2020-10-21 10:12
Hi there,

I can confirm this behavior. 

You can reproduce it configuring the ASG Min and Max capacity to 0. After that, you can create a service and try to create one task. 

Yes, [I know that there is a recommendation to not do that](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/asg-capacity-providers.html#asg-capacity-providers-considerations), but it is just a simulation to show that the error message is generic and hard to figure out depending on the issue.

These are the common error messages that should show from the task description:

- **No container instances were found in your cluster**
- **The port needed by the task is already in use**
- **Not enough memory for your tasks**
- **Not enough CPU units for your container instance**
- **Not enough available elastic network interface (ENI) attachment points**
- **A required attribute is missing for your container instance**
- **[AWS service] was unable to place a task because no container instance met all of its requirements.**

For this case, a message **No container instances were found in your cluster** should appear from the task description. This is the output of the `describe-tasks`:

```
{
  "Tasks": [
    {
      "Attachments": [],
      "Attributes": null,
      "AvailabilityZone": null,
      "CapacityProviderName": "CP",
      "ClusterArn": "arn:aws:ecs:eu-west-1:ACCOUNTID:cluster/CLUSTERNAME",
      "Connectivity": null,
      "ConnectivityAt": null,
      "ContainerInstanceArn": null,
      "Containers": [],
      "Cpu": "1024",
      "CreatedAt": "1603270236951",
      "DesiredStatus": "STOPPED",
      "ExecutionStoppedAt": null,
      "Group": "service:Service",
      "HealthStatus": "UNKNOWN",
      "InferenceAccelerators": null,
      "LastStatus": "STOPPED",
      "LaunchType": "EC2",
      "Memory": "512",
      "Overrides": {
        "ContainerOverrides": [],
        "Cpu": null,
        "InferenceAcceleratorOverrides": [],
        "ExecutionRoleArn": null,
        "Memory": null,
        "TaskRoleArn": null
      },
      "PlatformVersion": null,
      "PullStartedAt": null,
      "PullStoppedAt": null,
      "StartedAt": null,
      "StartedBy": "ecs-svc/8293770617925209047",
      "StopCode": "TaskFailedToStart",
      "StoppedAt": "1603270838572",
      "StoppedReason": "Task failed to start",
      "StoppingAt": "1603270838572",
      "Tags": [],
      "TaskArn": "arn:aws:ecs:eu-west-1:ACCOUNTID:task/294d42d2-b5b1-4b71-8247-83e4f233aa52",
      "TaskDefinitionArn": "arn:aws:ecs:eu-west-1:ACCOUNTID:task-definition/6901272881:10",
      "Version": "2"
    }
  ],
  "Failures": []
}
```

Please let me know if you need further information.

**Comment by AbhishekNautiyal** [comment] 2023-03-23 20:32
This has been fixed now!  Capacity provider error messages now include descriptive failure reasons to help troubleshoot 
https://aws.amazon.com/about-aws/whats-new/2023/03/amazon-ecs-contextual-task-launches-capacity-providers/

Closing this issue.  Please feel free to let us know if you have any feedback.

**Closed by AbhishekNautiyal** 2023-03-23 20:32 UTC
Labels: ECS, Proposed, Coming Soon
