### ISSUE TITLE
[ECS] Resources taken up by a "stopping" task are advertised as free

### ISSUE THREAD

**Issue by piotrb** [aws/containers-roadmap#575] opened 2019-11-07 06:59 UTC
### Summary
Tasks in desired status STOPPED seem to not count towards "used" resources on a host even if the task has not actually stopped yet.

### Description
When a task is asked to stop (ie sent TERM) and it handles the signal, but continues to operate. ECS advertises the container instance as no longer consuming the resources taken up by that task.

This then cascades into a secondary problem where the ECS service sees the free resources and schedules a new task onto that container instance. This task gets stuck in PENDING state until the unrelated other task finally terminates (or ECS_CONTAINER_STOP_TIMEOUT runs out).

This becomes especially apparent with higher values of ECS_CONTAINER_STOP_TIMEOUT where you can have a host pretend to have capacity when it does not for hours (with high values of ECS_CONTAINER_STOP_TIMEOUT)

### Expected Behavior
Until the underlying container actually stops, those resources should be counted as used so that the ECS agent does not schedule jobs onto a host that isn't free yet.

### Observed Behavior
The container instance shows the resources as free, ECS schedules new jobs onto it. Those jobs get stuck in PENDING until the original task finishes.

### Environment Details
Agent 1.32.1 via latest ecs optimized amazon linux ami

### Supporting Log Snippets
n/a

**Comment by coultn** [comment] 2019-11-27 20:19
Closing as this is a duplicate of #325 .

**Closed by coultn** 2019-11-27 20:19 UTC
Labels: ECS
