### ISSUE TITLE
[EKS] [Istio]: Add-on Feature Request for Istio Service Mesh in Amazon EKS 

### ISSUE THREAD

**Issue by malikdraz** [aws/containers-roadmap#1819] opened 2022-08-26 13:38 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Please provide an add-on feature to provision the EKS cluster with the Istio service mesh and the necessary configuration to provision NLB & ALB as ingress gateways depending on the requirements.

**Which service(s) is this request for?**
Elastic Kubernetes Service (EKS)

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

Kubernetes is a container orchestration technology that has many advantages, but it does come with flaws. There is currently no built-in out-of-the-box solution for traffic management (without scaling events) and security. This issue is solved by many service mesh. However, istio provides greater flexibility with a lot of end-to-end encryption out of the box. 

Currently, we have to deploy istio manually with profiles using istioctl or helm charts. Further, it requires additional changes to the istio operator if we want to configure the istio ingress gateway to use NLB or ALB in the AWS EKS cluster. This requires a lot of manual work with configuration. 

**Are you currently working around this issue?**
How are you currently solving this problem?

We are currently deploying the istio service mesh using istioctl or helm charts. 

**Additional context**
Anything else we should know?

Istio service mesh project is being submitted to CNCF: https://cloud.google.com/blog/products/open-source/submitting-istio-project-to-the-cncf

**Comment by mikestef9** [comment] 2022-08-29 03:58
Closing as duplicate of #1398

**Closed by mikestef9** 2022-08-29 03:58 UTC
Labels: EKS, Duplicate / Merged
