### ISSUE TITLE
EKS Auto Mode [Bug]: Karpenter does not launch nodes with tags in custom node class

### ISSUE THREAD

**Issue by vtgspk** [aws/containers-roadmap#2487] opened 2024-12-05 04:49 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

**Which service(s) is this request for?**
This could be EKS Auto

*I followed https://docs.aws.amazon.com/eks/latest/userguide/create-node-class.html to create a custom node class and node pool in my EKS Auto mode cluster 1.31. When I have tags in my node class as mentioned in the public doc, the karpenter is not launching any nodes. When I remove those, everything works fine. The node pool and the node class are in Ready state. The describe pod confirms that Karpenter detects this pod and had to be launched in the node claim of the custom node pool I created. But the node never comes up.  I dont see any Karpenter logs in Control plane as well. What is happening? Please advise

Nodepool yaml:

apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: va-eks-karpenter-default
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata: 
      labels:
        nodepoolName: va-eks-karpenter-default
    spec:
      expireAfter: 336h
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: va-eks-automode-default
      requirements:
      - key: nodepoolName
        operator: Exists
      - key: nodepoolName
        operator: In
        values:
        - va-eks-karpenter-default
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
        - on-demand
      - key: eks.amazonaws.com/instance-category
        operator: In
        values:
        - c
        - m
        - r
      - key: eks.amazonaws.com/instance-generation
        operator: Gt
        values:
        - "4"
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      terminationGracePeriod: 24h0m0s

Node Class yaml:

apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: va-eks-automode-default
spec:
  role: eks-shawtest-mng-eks-node-group
  # Required: Subnet selection for node placement
  subnetSelectorTerms:
    # - tags:
    #     Name: "<tag-name>"
    #     kubernetes.io/role/internal-elb: "1"
    # Alternative using direct subnet ID
    # - id: "subnet-0123456789abcdef0"
    - id: subnet-xxx
    - id: subnet-xxx
    - id: subnet-xx

  securityGroupSelectorTerms:
    # - tags:
    #     Name: "eks-cluster-node-sg"
    # Alternative approaches:
    # - id: "sg-0123456789abcdef0"
    # - name: "eks-cluster-node-security-group"
    - id: sg-xxxxxxx

  snatPolicy: Random  # or Disabled

  networkPolicy: DefaultAllow  # or DefaultDeny

  networkPolicyEventLogs: Disabled  # or Enabled

  ephemeralStorage:
    size: "80Gi"    # Range: 1-59000Gi or 1-64000G or 1-58Ti or 1-64T
    iops: 3000      # Range: 3000-16000
    throughput: 125 # Range: 125-1000

  tags:
    Environment: "production"
    Team: "platform"

Deployment:

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: harish-test-deployment
  name: harish-test-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-deployment
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        resources: 
          limits:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        nodepoolName: va-eks-karpenter-default
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

**Are you currently working around this issue?**
How are you currently solving this problem?
Removing Tags from nodeclass works

**Additional context**
Is there any way we can view the Karpenter logs to troubleshoot? 

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by fbuzila-g2** [comment] 2024-12-06 19:04
I confirm I have the same issue, tags on NodeClass are not wworking

**Comment by jatinmehrotra** [comment] 2024-12-07 09:57
@vtgspk 

How did you managed to create custom node class? 

- Did you enabled EKS auto on existing cluster or on a new cluster?
- i am trying to create custom node class with IAM role and everytime it says `Role CustomNodeClassRole is unauthorized to join nodes to the cluster`


My node class is something like 

```
apiVersion: karpenter.k8s.aws/v1
kind: EKSNodeClass
metadata:
  name: custom
spec:
  ephemeralStorage:
    size: "160Gi"
  role: CustomNodeClassRole
  subnetSelectorTerms:
    - id: "zzzzz"
    - id: "zzzz"
  securityGroupSelectorTerms:
    - id: "xxxx
```

**Comment by vtgspk** [comment] 2024-12-19 00:49
Adding the below inline policy to the Cluster role fixes the issue



{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Compute",
            "Effect": "Allow",
            "Action": [
                "ec2:CreateFleet",
                "ec2:RunInstances",
                "ec2:CreateLaunchTemplate"
            ],
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "aws:RequestTag/eks:eks-cluster-name": "${aws:PrincipalTag/eks:eks-cluster-name}"
                },
                "StringLike": {
                    "aws:RequestTag/eks:kubernetes-node-class-name": "*",
                    "aws:RequestTag/eks:kubernetes-node-pool-name": "*"
                }
            }
        },
        {
            "Sid": "Storage",
            "Effect": "Allow",
            "Action": [
                "ec2:CreateVolume",
                "ec2:CreateSnapshot"
            ],
            "Resource": [
                "arn:aws:ec2:*:*:volume/*",
                "arn:aws:ec2:*:*:snapshot/*"
            ],
            "Condition": {
                "StringEquals": {
                    "aws:RequestTag/eks:eks-cluster-name": "${aws:PrincipalTag/eks:eks-cluster-name}"
                }
            }
        },
        {
            "Sid": "Networking",
            "Effect": "Allow",
            "Action": "ec2:CreateNetworkInterface",
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "aws:RequestTag/eks:eks-cluster-name": "${aws:PrincipalTag/eks:eks-cluster-name}"
                },
                "StringLike": {
                    "aws:RequestTag/eks:kubernetes-cni-node-name": "*"
                }
            }
        },
        {
            "Sid": "LoadBalancer",
            "Effect": "Allow",
            "Action": [
                "elasticloadbalancing:CreateLoadBalancer",
                "elasticloadbalancing:CreateTargetGroup",
                "elasticloadbalancing:CreateListener",
                "elasticloadbalancing:CreateRule",
                "ec2:CreateSecurityGroup"
            ],
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "aws:RequestTag/eks:eks-cluster-name": "${aws:PrincipalTag/eks:eks-cluster-name}"
                }
            }
        },
        {
            "Sid": "ShieldProtection",
            "Effect": "Allow",
            "Action": [
                "shield:CreateProtection"
            ],
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "aws:RequestTag/eks:eks-cluster-name": "${aws:PrincipalTag/eks:eks-cluster-name}"
                }
            }
        },
        {
            "Sid": "ShieldTagResource",
            "Effect": "Allow",
            "Action": [
                "shield:TagResource"
            ],
            "Resource": "arn:aws:shield::*:protection/*",
            "Condition": {
                "StringEquals": {
                    "aws:RequestTag/eks:eks-cluster-name": "${aws:PrincipalTag/eks:eks-cluster-name}"
                }
            }
        }
    ]
}

**Comment by mikestef9** [comment] 2024-12-19 01:41
Yes you need that extra permissions on the cluster role. Closing as mainly duplicate of #2495

**Closed by mikestef9** 2024-12-19 01:41 UTC
Labels: EKS, Proposed, EKS Auto Mode
