### ISSUE TITLE
EKS Feature Request: Allow customer to choose Calico CNI

### ISSUE THREAD

**Issue by trimbleAdam** [aws/containers-roadmap#186] opened 2019-03-05 17:35 UTC
**Tell us about your request**
As an existing Kops user, I am able to choose which CNI/overlay works best for my workloads. We require the ability to choose which CNI implementation is applied to cluster at creation time.

Particularly interested in end-to-end Calico CNI, or kubenet + Calico.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Our workloads require lots of small pods to be binpacked on EC2 minions. Currently a m5.large fits our workloads perfectly within a Kops kubernetes cluster, so the limitation of 29 pods per instance becomes a big waste of money.

**Are you currently working around this issue?**
80% of our workloads are remaining on Kops cluster until EKS supports our workloads.
For the other 20% we are trying to get cluster-autoscaler to take MAX_PODS into consideration during scale out/in.

**Additional context**
Had a great call! We look forward to making a switch to EKS.

**Attachments**
See case # 5756612121.

**Comment by tabern** [comment] 2019-07-04 04:10
@trimbleAdam check out https://github.com/aws/containers-roadmap/issues/398 and let us know what you think. We think this should solve your binpacking need.

**Comment by adaughterson** [comment] 2020-02-19 22:09
We are looking at EKS again, and just wanted to actually put some thought in to a reply.

I read through the thread, and it looks like there is a big desire to make this very thing possible, but I also see a few "any word on this?" posts. 

Still want this FR, or one which provides the equivalent net outcome (eg: pod density issues caused by using VPC secondary IP addresses mitigated by allowing the specification of CIDR).

Thanks!

Adam Daughterson

**Comment by andelhie** [comment] 2020-02-19 22:45
I just ran in to this problem right now.  The ability to have the Calico CNI native to the EKS setup is key.  Setting up a secondary CIDR to then have a limits IP range per the NIC to ENI IP limit is very limiting.  I know as a fact that i can fit more pod than 11 on a m4.large instance.

**Comment by kshafiee** [comment] 2020-02-21 16:30
Hi team, any updated on this?

**Comment by jwenz723** [comment] 2020-03-11 15:01
I would love to be able to specify to use a CNI other than the AWS VPC CNI. Would love to see some movement on this issue.

**Comment by Vitorspk** [comment] 2020-03-26 16:51
good feature developer option to another CNI on creating EKS.

**Comment by bjethwan** [comment] 2020-05-15 11:23
VPC IP CIDR range is a scarce resource for large orgs,
with multiple networks, both on-premise & on-cloud connected together.
(secondary cidr ranges are already in use)
 
aws-vpc-cni helped me greatly in one of the uses-cases, wherein I wanted to run couchbase on k8s (as described [here](https://medium.com/@AtFlash/couchbase-in-multi-kubernetes-cluster-environment-challenges-vs-available-options-cb01a107fffd)).

But having aws-vpc-cni as the only option for EKS is limiting.

**Comment by mszumilak** [comment] 2023-02-02 13:43
So far nobody mentioned it so it is worth adding that using calico on EKS as the only CNI makes using webhooks difficult. Control plane does not understand Calico so the only way to use webhooks is to expose them on the host network or via ingress. Both of those workarounds are awful and might be insecure.

**Comment by mikestef9** [comment] 2024-04-11 21:59
We have no plans to add Calico as a native feature of EKS, and will close this issue. However, we will soon launch #923 which will make it much easier to install an alternate CNI like Calico in a new EKS cluster.

**Closed by mikestef9** 2024-04-11 21:59 UTC
Labels: EKS, Not planned, Proposed
