### ISSUE TITLE
[ECS] One task prevents from all of the other in instance to change from PENDING to RUNNING 

### ISSUE THREAD

**Issue by Alonreznik** [aws/containers-roadmap#325] opened 2018-11-01 09:48 UTC
Hello There.
We're facing lately a strange practice from ECS about tasks that prevent from new tasks to run in an instance. 

A little about our case - 
We have some tasks that need to complete their action and then exit by themselves in a stopTask command. That means we have a gracefull-shutdown process, that in sometimes make some time to complete (more than few seconds and even some long minutes).

However, when a stopTask is sent over these tasks, they do not appear anymore in the tasks at ECS console (which is fine), but they also make all other tasks in the same instance that are trying to change their state from `PENDING` to `RUNNING`. 

Here is an example of one instance tasks when it happens:
![image](https://user-images.githubusercontent.com/8024926/47844999-76bd8980-ddcc-11e8-8f8c-cf4e480a0e30.png)

Why is that behavior happens? Why one task prevent from the other to run next to it until it done? This is a bad practice in resource management (we don't use the max potential of our instances at the pending time).

The best thing will be that the stopped task will appear in the console until it really stopped in the instance, and the state changing from `PENDING` to `RUNNING` won't be affected by other tasks in the same instance.

I hope you can fix that behavior,

Thanks!

**Comment by Alonreznik** [comment] 2019-08-23 23:09
Hi @coultn @adnxn 
Any update or ETA about that?

Thank you

Alon

**Comment by Alonreznik** [comment] 2019-10-06 08:53
Hi Guys.
Can somebody take a look about that?
This is harming our business because we have a problem with deploying new versions to our Prod. This is really problemtaic, and it shades a dark light about continuing using the ECS in our side.

Thanks

**Comment by Alonreznik** [comment] 2019-10-10 15:48
@coultn

**Comment by coultn** [comment] 2019-10-10 20:05
Hi, thank you for your feedback on this issue.  We are aware of this behavior and are researching solutions.  We will keep the github issue up to date as the status changes.

**Comment by Halama** [comment] 2019-10-31 11:46
I've discussed this with [Nathan](https://twitter.com/nathankpeck/status/1182312248716517377) he told me that they  plan fixing this, but unfortunately without a quick fix. We have similar issues with deployment and scaling and due to it lot of unnecessary rolls of new instances.

Meanwhile we are experimenting with EKS (also fo multi-cloud deployment) where this issue isn't present.

**Comment by Alonreznik** [comment] 2019-10-31 11:58
> I've discussed this with [Nathan](https://twitter.com/nathankpeck/status/1182312248716517377) he told me that they plan fixing this, but unfortunately without a quick fix. We have similar issues with deployment and scaling and due to it lot of unnecessary rolls of new instances.
> 
> Meanwhile we are experimenting with EKS (also fo multi-cloud deployment) where this issue isn't present.

Hi @Halama .

Thanks for the reply and the update.

I can get this is not something that can be quick to solve, but meanwhile, ECS team can provide workarounds, such as placing-method of binpack and the newest instances, or determine the time task can be on PENDING state before it tries on the new instances. This issue is not getting any response due to many users encountering that. It is open more than a year and they're can't send any reasonable ETA (even 3 months is good for us). It was on "researching" just in the last week.

Can you please share about your migration process to EKS from ECS?

Thanks again

Alon

**Comment by coultn** [comment] 2019-10-31 21:07
@Alonreznik, would you be willing to share more details about your specific configuration via email?  ncoult AT amazon.com.
Thanks

**Comment by Alonreznik** [comment] 2019-11-05 11:06
hi @coultn.
Thanks for your option. 
Just sent a detailed email with our architecture and configuration, and the problem we're facing.

Thanks, and appreciated!

Alon

**Comment by Alonreznik** [comment] 2020-01-30 09:59
Hi Guys.
We've actually faced this again today at the prod, where there was a huge gap for almost an hour between the desired task and the running task. This is not something we can still rely on, and it let a big shade on using ECS on production for our main system, because it means the PENDING tasks are just "stucking" the entire instance and we need to refresh the entire task placement again every time it happens.

In the next graph, you can see the gaps:

![image](https://user-images.githubusercontent.com/8024926/73438843-5d044c80-4357-11ea-96b1-a9b67ae66964.png)

The green is the desired task number per minute, and the orange is actual number of the running tasks. At some point in time, there were more than 70 tasks asked for starting and got stuck because of one (!!!) task that is still running on each instance. We don't also have the ability to set new tasks on new instances only, so nothing we can do about that.

This is a big lack of the service, and makes it unstable in our terms. 
Please fix it as soon as possible,

Alon

**Comment by coultn** [comment] 2020-01-30 15:39
@Alonreznik Yes, this is a known issue (as we have discussed previously).  Here is one solution that we are considering implementing soon:
1.  Introduce a new subject field for the ECS [cluster query language](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cluster-query-language.html), called stoppingTaskCount.  This would be similar to the existing field called runningTaskCount, except that it would be the count of tasks on an instance that are in the STOPPING state.
2. With this new subject field, you could use a placement constraint of this form:
```
"placementConstraints": [
    {
        "expression": "stoppingTaskCount == 0",
        "type": "memberOf"
    }
]
```

This placement constraint would prevent the task from being placed on any instance that has a stopping task.  So,  new tasks would only be placed on instances with no stopping tasks.  Please let us know if you have questions/comments about this proposed solution.

**Comment by tom22222** [comment] 2020-01-30 20:37
Hi @coultn Thanks for the update on this.  How would this work in this example scenario:

I have 1 ecs cluster with 10 ec2 instances, ECS_CONTAINER_STOP_TIMEOUT is set to 6 hours.  I have a service with 10 tasks that are distributed evenly over all 10 nodes (1 task per node).  I tell the service to scale in to 0 tasks but the tasks are currently busy so they stay in a stopping state until they have finished their work (or 6 hours expires).  I then try to create another service on the same cluster while these long running tasks are still completing but, despite there potentially being lots of cpu and memory available, the other service is not able to start?  In my mind this still means the whole cluster is essentially locked for up to 6 hours.  Or am I misunderstanding the proposed solution here?

I don't know the full details of how ECS works but it seems more sensible to me to base the allocation of tasks to the hosts based on the actual free cpu and memory of that host (total cpu / ram minus (tasks running + tasks stopping))  If there are tasks stopping on a host you should still be able to start tasks on that host if there is sufficient resource, when the tasks finally stop you tell ECS the cpu / ram resource has become available.

**Comment by coultn** [comment] 2020-01-30 20:55
@tom22222 In your specific scenario, I would recommend (1) sizing the instances as close as possible to the task size (since you are only running 1 task per instance) and (2) enabling cluster auto scaling - this will cause your cluster to scale out to accommodate the new service automatically, assuming the placement constraint feature is implemented as I proposed above.

However, we may also implement additional changes to account for stopping tasks’ resources as you proposed, but at the present time the placement constraint approach will be quicker to launch.  The reason for this is that the idea you proposed above would change the default behavior of task placement for all customers, even if they are not having the problem described in this issue.  We typically approach changing default behavior for all customers more slowly than a feature that doesn’t change default behavior but which can be opted into for those customers that need it (such as the placement constraint approach I proposed above).

**Comment by tom22222** [comment] 2020-01-31 14:04
Hi @coultn 

Thanks for the response. So on your suggestions:

> I would recommend (1) sizing the instances as close as possible to the task size (since you are only running 1 task per instance) 

I just gave that as an example of how 1 service could be configured, we could be running lots of other services with tasks of various sizes on the cluster at the same time and the issue would still be the same

> (2) enabling cluster auto scaling 

Yes, I agree, using the new Capacity Provider stuff along with your proposed change here could work and should allow for new services to be started although the drawbacks here would be that it would take some time to spin up additional ec2 instances to handle the new task requirements and all of the existing ec2 instances are still locked despite the fact they have plenty of cpu / ram available (so we will therefore have poor scaling performance across the whole cluster and we are wasting resources).  Don't get me wrong, I do think this is better than what we have now but it feels more of a workaround with some drawbacks.

> We typically approach changing default behavior for all customers more slowly than a feature that doesn’t change default behavior but which can be opted into for those customers that need it

I completely agree there would be a risk in changing the default behaviour so I would suggest you have it as another option where the default is the current behaviour ..... 

ECS_CONTAINER_STOPPING_TASK_PROCESSING=completed (this would be the current way it works)
ECS_CONTAINER_STOPPING_TASK_PROCESSING=immediate (this would allow other tasks to be started even if there were tasks in a stopping state)

(I'm sure you can think of better option names but hopefully you get my point)

Thanks

**Comment by Halama** [comment] 2020-04-26 09:10
The issue also affects DEAMON services. Daemon containers doesn't start on new instance in case there are RUNNING daemon containers in desired state STOPPED on DRAINING instances.
I think it is because the Automatic Desired Count of DAEMON service also counts the RUNNING container in Desired Status STOPPED.

**Comment by rs-garrick** [comment] 2020-06-19 21:39
I'm also trying to take advantage of a long stopTimeout. Preventing new tasks from running only makes sense when the stopTimeout is only a few seconds. Now that stopTimeout can be very long, having stuck ECS hosts is silly.

I propose that tasks should not deregister from the service until after the container has actually exited. The task should enter a new state called `STOPPING` once the initial `stop` has been sent to the container. In this way the resources are still tracked and scheduling new tasks can be assigned appropriately. After the container exits, then the task can move into STOPPED and deregistered.

**Comment by Alonreznik** [comment] 2020-07-11 14:40
Any update with this one?

**Comment by Alonreznik** [comment] 2020-10-21 07:53
@coultn any update in here?
Something that may be an option?

This is 2 years old issue!

**Comment by thom-vend** [comment] 2021-06-01 02:50
Hi, @pavneeta any update on this issue ?

**Comment by Alonreznik** [comment] 2021-10-14 12:33
BTW - 3 years (!!!!) after this issue had been opened, and still many people facing this unexpected behaviour. I think this is a good reason to make it fixed once for good.

**Comment by Alonreznik** [comment] 2021-11-30 18:12
Hi @petderek. Any update?

**Comment by markdascher** [comment] 2022-10-12 19:52
AWS seems to be overly cautious regarding a fix, and I think it's because the issue still isn't clearly understood by everyone involved. I'm not entirely sure that I understand it myself, but after reading the whole thread, here's what it seems to boil down to:

1. A 40 GB host has a single 10 GB task. It can start three more 10 GB tasks just fine. Everyone is happy.
2. The same 40 GB host has the same 10 GB task, but now that task is stopping. Suddenly we can't start any new tasks on this host, even though there are 30 GB available.

Scenario 2 makes no sense. It's clearly a bug. The phrase "by design" doesn't belong in this thread. I understand how it could've happened though–it's perhaps an unfortunate workaround for an older bug:

* Bug A: When tasks are stopping, the system calculates available resources incorrectly. Perhaps the calculation shows "40 GB free" instead of "30 GB free."
* Bug B: Rather than fixing Bug A, the ECS Agent includes logic to know when the calculation is incorrect, and then decides to freeze (with potentially catastrophic consequences) during that timeframe.

Is that accurate? Are we actually worried about the unintended consequences of fixing Bug A?

In our case shortening stopTimeout isn't a viable option, and neither are placementConstraints. Every host may have tasks stopping at the same time, so placementConstraints would just continue making them all unusable. (And even in a best case, it would result in very suboptimal placement as everything gets squeezed onto a small number of usable hosts.)

Two possible fixes:
* When tasks are stopping, continue calculating available resources correctly. In the example above, that means there are only 30 GB free until the container is actually gone.
* If that's too drastic, then at least make the ECS Agent try harder. If tasks are stopping, make the ECS Agent correct the calculations locally, and continue if it's safe to do so. If you're unlucky and tasks get placed onto a host that's actually full, then you're out of luck. But that's still way better than where we are now, and at least isn't completely baffling behavior.

**Comment by AbhishekNautiyal** [comment] 2023-06-30 18:49
We are excited to share that we've addressed the known issue in ECS Agent to prevent tasks stuck in pending state on instances that have stopping tasks with long timeouts.  For details on the root cause, fix, and other planned improvements, please see [What's New Post,](https://aws.amazon.com/about-aws/whats-new/2023/06/amazon-ecs-tasks-faster-prolonged-shutdown/)  [Blog Post](https://aws-preview.aka.amazon.com/about-aws/whats-new/2023/06/amazon-ecs-tasks-faster-prolonged-shutdown/), and [documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-resource-accounting.html)

We'll be closing this issue. As always, happy to receive your feedback. Let us know if you face any other issues.

**Comment by Alonreznik** [comment] 2023-07-03 19:17
Holy moly!!! 5 years!! Amazing guys! I'm so excited!

**Closed** 2023-07-27 22:26 UTC
Labels: ECS, Proposed, Coming Soon
