### ISSUE TITLE
[EKS] [request]: Autoscaling Groups created by Managed NodeGroups do not output metrics

### ISSUE THREAD

**Issue by Chili-Man** [aws/containers-roadmap#1216] opened 2021-01-09 01:44 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

We would like an option to enable the Auto Scaling group metrics collection for Managed NodeGroups in order to monitor the autoscaling metrics

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

We'd like to be able to run various analyses on the node groups such cost optimization, length of time it took to scale up, etc.   

**Are you currently working around this issue?**
We're manually enabling it directly through the ASGs that are created by the managed node groups.

**Comment by mikestef9** [comment] 2021-04-27 03:26
Closing as duplicate of #762

**Closed by mikestef9** 2021-04-27 03:26 UTC
Labels: EKS, EKS Managed Nodes, Proposed
