### ISSUE TITLE
[EKS] [request]: Add API to list available EKS versions

### ISSUE THREAD

**Issue by igaskin** [aws/containers-roadmap#1937] opened 2023-01-18 19:55 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
In order to better facilitate regular upgrades of EKS clusters, we would like to programmatically retrieve a list of available EKS versions.  This would allow for triggering workflows when new cluster versions become available, such as; sending email notifications, running `cluster-update` commands, filing tickets, running tests, etc.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

We would like to reduce necessity of human attentiveness required to engage the variety of work involved with upgrading EKS clusters.  Via the use of a `list-kubernetes-versions` API, we can automate the manual tasks organizations do when beginning evaluate upgrading EKS clusters

**Are you currently working around this issue?**
Workarounds either involve parsing `describe-addon-verions` repsonses, as described here: https://stackoverflow.com/a/71448603

Or scraping available versions from the official docs: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#available-amazon-eks-kubernetes-versions

**Comment by stevehipwell** [comment] 2023-01-25 14:58
You can explore the EKS artifacts with `aws s3 ls s3://amazon-eks/` which at least gives you an overview of the problem space.

**Comment by mikestef9** [comment] 2024-12-20 22:23
Closing as duplicate of #982

**Closed by mikestef9** 2024-12-20 22:23 UTC
Labels: EKS, Proposed, Duplicate / Merged
