### ISSUE TITLE
[EKS] [request]: Support Cilium CNI in EKS add-ons

### ISSUE THREAD

**Issue by saravanan30erd** [aws/containers-roadmap#2137] opened 2023-09-05 13:30 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Support Cilium CNI in EKS add-ons

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
With this issue solved, it's easy to build a EKS cluster in which we can use cilium as CNI.

**Are you currently working around this issue?**
After EKS installation, deploying cilium CNI separately.

**Comment by sjastis** [comment] 2023-09-05 15:16
This is a duplicate of #1870

**Closed** 2023-09-05 15:54 UTC
Labels: EKS, Proposed, EKS Add-Ons, Duplicate / Merged
