### ISSUE TITLE
Image Signing Support in ECR

### ISSUE THREAD

**Issue by DrFaust92** [aws/containers-roadmap#43] opened 2018-12-12 14:27 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Support for storing image signatures in ECR. 

**Which service(s) is this request for?**
Storing container image signatures in ECR, verification of signatures in ECS/EKS.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Notary V1 is the currently available community-supported tool that would allow for signing and verifying OCI/Docker images, but it requires standing up a separate service and a lot of heavy lifting that each customer must do to setup and maintain. 

**Are you currently working around this issue?**
N/A

**Additional context**

Update from ECR team (10/14):

We are actively working on adding support for container image signing in ECR. To deliver this feature, AWS is participating in two parallel open source efforts to deliver support for storing signatures (and other related artifacts) in an OCI registry and performing signature validation in a container orchestrator so we can launch a solution that will be compatible across container orchestrators and OCI registries. 

* To enable the storage and discovery of “reference artifacts”, such as signatures, in an OCI registry, we are working with the ORAS project to define a new specification for [OCI Artifacts](https://github.com/oras-project/artifacts-spec). Last month, we were excited to announce an [initial draft release](https://github.com/oras-project/artifacts-spec/releases/tag/1.0.0-draft.1) for that project! 
* We are also participating in the design and development of [Notary V2](https://github.com/notaryproject/notaryproject), to define industry standards for signing and validating images that can be implemented in the tools used to build images today and container orchestrators like EKS & ECS.

We will update this issue when we reach key milestones, but for an up to date picture of our progress, please take a look at the respective projects. We’re always looking for feedback and collaborators, so join us in the [oras-project/artifacts-spec](https://github.com/oras-project/artifacts-spec) & [notaryproject/notaryproject](https://github.com/notaryproject/notaryproject) repositories!

**Comment by jtoberon** [comment] 2018-12-18 04:43
Thanks for feedback, @DrFaust92. We've started to discuss how we want this to work for our customers. It's a surprisingly complicated topic though, so we don't have a proposal to share yet. We're going to leave this open as a placeholder.

**Comment by DrFaust92** [comment] 2019-07-23 07:20
Any update on this?

**Comment by omerfsen** [comment] 2019-08-19 17:16
Would be great to see it on AWS ECR. Also I think until it is out we can run our own notary server and then after signing docker image via Notary then push it to ECR

**Comment by jmb12686** [comment] 2019-11-15 23:44
Any update or insight into the status of this for ECS?  Image SHA tracking was announced for ECS https://aws.amazon.com/about-aws/whats-new/2019/10/amazon-ecs-now-supports-ecs-image-sha-tracking/ , however it's not clear if this fulfills the trusted content requirement.

**Comment by omieomye** [comment] 2019-12-17 22:25
Update: as part of a broader community 'Notary v2' initiative, ECR will participate and contribute with a view to apply that specification to our effort tracked by this issue.  Its an open group with multiple cloud and on-premise vendors working together, with the kickoff meeting held on 12/12 here in Seattle.

**Comment by jmb12686** [comment] 2019-12-18 00:54
@omieomye , Thank you for providing an update and transparency into the current state of container signing within the broader community.  Aside from listening to the [kick-off meeting](https://youtu.be/mZ_x0KW33Tg), how can users get involved in the discussion?

**Comment by jtoberon** [comment] 2019-12-18 05:59
Call in details for the OCI weekly meeting is available here: https://github.com/opencontainers/org. You also can join the relevant IRC and Slack channels, which are linked from the same github page.

**Comment by jonassteinberg1** [comment] 2020-05-23 06:51
Am I correct in thinking that notary cannot be used with ecr still?

**Comment by phene** [comment] 2020-06-05 16:53
You can sign a container with a notary when pushing to ECR, but ECS doesn't support verification.

**Comment by chrisdipesa** [comment] 2020-06-13 18:32
Yup. https://awscloudcontainersconference.splashthat.com/ Everyone should attend this event. 

Security Best Practices with Amazon ECR
Omar Paul, Sr Product Manager, ECR 

We have questions for Omar!

**Comment by jonassteinberg1** [comment] 2020-06-13 18:56
I am attending it already.  So your saying Omar is going public with the Notary feature in that talk?

**Comment by omieomye** [comment] 2020-06-13 20:18
Our progress on Notary is tracked by this issue, and we're actively participating towards a [Notary v2](https://github.com/notaryproject) specification. On the [summit presentation](https://awscloudcontainersconference.splashthat.com/), I would love to get feedback what the ECR community wants us to tackle. Tweet or DM @omieomye and we'll go from there.

**Comment by cloudsriseup** [comment] 2020-07-09 23:46
Currently slated 2021 with Notary v2 per Omar's presentation linked by @chrisdipesa above.  Are there any other compensating controls one could perform to meet this need until 2021?

**Comment by jnaulty** [comment] 2020-09-10 20:22
Hey @omieomye and @chrisdipesa 
I'm curious to know if there are any slides or recording from the summit presentation. The links provided no longer work.

**Comment by kapilt** [comment] 2020-09-11 13:21
seems this issue is missing any context on why v2, so adding in some links

high level blog post on v2 - https://www.docker.com/blog/community-collaboration-on-notary-v2/
v2 requirements - https://github.com/notaryproject/requirements
working group meeting notes - https://hackmd.io/_vrqBGAOSUC_VWvFzWruZw

**Comment by renkenk** [comment] 2020-10-02 11:55
+1

**Comment by knksmith57** [comment] 2020-12-01 21:36
With [the release of ECR Public](https://aws.amazon.com/blogs/aws/amazon-ecr-public-a-new-public-container-registry/), this seems more relevant and valuable than ever.

**Comment by bjethwan** [comment] 2021-04-12 15:08
Any update on this? 
Is there a tentative release date attached to this? 
It's more 5 months since the last comment on this issue.

**Comment by dlorenc** [comment] 2021-04-12 17:54
For people here interested in container signing in general, feel free to checkout github.com/sigstore/cosign. It should already work well with ECR.

**Comment by ari-becker** [comment] 2021-04-13 08:13
> For people here interested in container signing in general, feel free to checkout github.com/sigstore/cosign. It should already work well with ECR.

@dlorenc does it work with ECR? The project doesn't specify ECR as being supported.

**Comment by 06kellyjac** [comment] 2021-04-13 08:32
```
$ cosign sign -key cosign.key dlorenc/demo
Enter password for private key:
Pushing signature to: index.docker.io/dlorenc/demo:sha256-87ef60f558bad79beea6425a3b28989f01dd417164150ab3baab98dcbf04def8.cosign
```

It looks like `cosign` pushes an "image" holding the signing details to a label called `sha256-blahblah.cosign` so it's only using very normal features of a basic image registry

> cosign uses go-containerregistry for registry interactions, which has excellent support, but some registries may have quirks.

As long as ECR doesn't behave wildly different to all the other registries it should work just fine.
I saw one ECR related issue in https://github.com/google/go-containerregistry but that's been resolved

**Comment by dlorenc** [comment] 2021-04-13 10:37
I don't have any AWS credentials so I haven't been able to test it. That "supported" list is really just a list of registries people have confirmed it works with. If anyone tries it out, please feel free to send a PR adding the entry!

We don't do anything not allowed by the existing OCI specifications so I'd be surprised if it doesn't work, but a few registries do have some quirks here.

**Comment by netflash** [comment] 2021-06-19 02:43
Appreciate it if we could get any updates on this from AWS people.

**Comment by mkinage** [comment] 2021-06-22 05:00
We are working on configuring Docker trust using cosign with AWS ECR. I am able to sign Docker image but getting the below error while running a Docker. 
Error: remote trust data does not exist for does not have trust data for awsaccno.dkr.ecr.us-west-2.amazonaws.com/testapp
Please let me know if I missed anything,

**Comment by dnx-seek** [comment] 2021-06-22 05:04
@mkinage I think you should raise that on the [cosign repo](https://github.com/sigstore/cosign). Sounds to me like you didn't push the sig.

**Comment by mkinage** [comment] 2021-06-22 05:07
Thank you. I will update on the cosign repo.

**Comment by dlorenc** [comment] 2021-07-02 14:35
Closing the loop: @mkinage got everything working over in https://github.com/sigstore/cosign/issues/383#issuecomment-873038483

**Comment by ramkama87** [comment] 2021-08-12 15:00
Hello AWS/ @omieomye  - Do you have any timelines on when AWS natively supports the signing of images?

**Comment by michaelb990** [comment] 2021-10-14 21:17
Hey all -- I've updated the issue's description (thanks for filing @DrFaust92). We are actively working on this, and I'm including the latest update from the team below:

We are actively working on adding support for container image signing in ECR. To deliver this feature, AWS is participating in two parallel open source efforts to deliver support for storing signatures (and other related artifacts) in an OCI registry and performing signature validation in a container orchestrator so we can launch a solution that will be compatible across container orchestrators and OCI registries. 

* To enable the storage and discovery of “reference artifacts”, such as signatures, in an OCI registry, we are working with the ORAS project to define a new specification for OCI Artifacts (https://github.com/oras-project/artifacts-spec). This week, we were excited to announce an initial draft release (https://github.com/oras-project/artifacts-spec/releases/tag/1.0.0-draft.1) for that project! 
* We are also participating in the design and development of Notary V2 (https://github.com/notaryproject/notaryproject), to define industry standards for signing and validating images that can be implemented in the tools used to build images today and container orchestrators like EKS & ECS.

We will update this issue when we reach key milestones, but for an up to date picture of our progress, please take a look at the respective projects. We’re always looking for feedback and collaborators, so join us in the oras-project/artifacts-spec (https://github.com/oras-project/artifacts-spec) & notaryproject/notaryproject (https://github.com/notaryproject/notaryproject) repositories!

**Comment by JohnPreston** [comment] 2021-12-01 07:44
What is the update after the re:Invent leadership session on notary + ECR ?

**Comment by jeffery-jen** [comment] 2021-12-30 03:26
Would like to see an update on this.

**Comment by jlbutler** [comment] 2022-12-14 02:50
Quick update on this, sorry it could have been made sooner. Since the last update, members of the ECR team joined others in the formation of the OCI's working group for reference types. This resulted in new 1.1 versions of the OCI Image and Distribution specs, providing OCI Artifacts and a new Referrers API. With these features, we can leverage an open specification for managing image signatures as well as other artifact types in ECR.  We've partnered with another service team to bring a managed image signing experience to AWS, based upon Notary v2. Both of these projects are nearing a GA, at which point we can share with you all the work we've been doing. We will update here when we have more specifics to share. Thanks for your patience, and more soon!

**Comment by NikolaySokolov** [comment] 2023-01-27 23:33
@jlbutler is there any updates on this topic? We are at the point either waiting for this to be available or creating our own solution. Can you please give us more details on when it can be expected?

**Comment by SamirPS** [comment] 2023-02-09 16:38
@jlbutler Are there any updates on the topic of the ORAS artefact? Especially for attaching a file to an ECR image with oras attach?

**Comment by jlbutler** [comment] 2023-02-23 03:57
Hi all, sorry for the delay. Quite a bit has changed while we continue to work upstream on the OCI 1.1 specs. As things are still in flux there, we've been working with the client-side fallback references support for ECR. That's now working, which unblocks some pieces of the overall picture.

The Notary v2 client has now implemented support for references within the scope of OCI 1.0, and you can use the 1.0.0-rc2 release of Notation with ECR. We are still working on a more managed solution, but this is something to look at to get an idea of the workflow of signing an image. We'll put a blog out on that soon, and as soon as we have more to share about a managed solution, we'll certainly update here.

**Comment by jlbutler** [comment] 2023-02-23 04:00
> @jlbutler @michaelb990 Are there any updates on the topic of the ORAS artefact? Especially for attaching a file to an ECR image with oras attach?

The ORAS Artifact work moved into the OCI, but that said you can use the latest oras CLI to attach with ECR. Note until the 1.1 spec is released, you'll need to use the `--image-spec v1.1-image` option.

e.g.

```
$ oras attach --image-spec v1.1-image --export-manifest test-manifest.json --artifact-type test/example 1234.dkr.ecr.us-west-2.amazonaws.com/oras-test:latest ./test.txt
Uploading 524b162ec8ad test.txt
Uploaded  524b162ec8ad test.txt
Attached to [registry] 1234.dkr.ecr.us-west-2.amazonaws.com/oras-test@sha256:4c524d1407ad83d60e4324050668d3ee77af96f2a88d0ff418ecbbcad502449d
Digest: sha256:d9cc47b48144f19dd56ecd757286208ac2f0dc33e22dbe50cd41055214dfab25
```

**Comment by SamirPS** [comment] 2023-02-23 09:29
@jlbutler i have this error with ecr public

```oras attach -v --artifact-type "application/spdx+json" public.ecr.aws/rocksdev/artifact-test:lunar empthyone.json -u AWS -p $(aws ecr-public get-login-password --profile ociimage) --image-spec v1.1-image --export-manifest test-manifest.json
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Preparing empthyone.json
Exists    44136fa355b3 application/spdx+json
Exists    ca3d163bab05 empthyone.json
Exists    678c136e4e91 application/vnd.oci.image.index.v1+json
Uploading a8ddde0d870c application/vnd.oci.image.manifest.v1+json
Error: PUT "https://public.ecr.aws/v2/rocksdev/artifact-test/manifests/sha256:a8ddde0d870c85f4afd502f3df4b9695a94b9e83c0810eb211db1c2e835b3ffa": response status code 405: unsupported: Invalid parameter at 'ImageManifest' failed to satisfy constraint: 'Invalid JSON syntax'
```

**Comment by jlbutler** [comment] 2023-02-28 03:22
Hi @SamirPS. Sorry about that, I should have been more specific. In ECR, we have done some work to support the recent changes in ORAS client and client-side artifact support in general.  This work is ongoing in ECR Public at the moment, and will be available soon. I will post back here when that work is complete.  Thanks!

**Comment by jlbutler** [comment] 2023-06-01 11:44
> Hi @SamirPS. Sorry about that, I should have been more specific. In ECR, we have done some work to support the recent changes in ORAS client and client-side artifact support in general. This work is ongoing in ECR Public at the moment, and will be available soon. I will post back here when that work is complete. Thanks!

I completely neglected to reply back here as I said I would - apologies @SamirPS. Client-side reference types are supported in ECR Public now.

**Comment by SamirPS** [comment] 2023-06-01 11:46
@jlbutler Thanks for the information

**Comment by jlbutler** [comment] 2023-06-06 23:10
Hi all. It's been quite a long road, but we have launched a managed signing solution today with AWS Signer's new Container Image Signing capability. 

Launch blog is a good place to get started, please let us know what you think. Thanks so much for your patience along the way!

https://aws.amazon.com/blogs/containers/announcing-container-image-signing-with-aws-signer-and-amazon-eks/

**Closed** 2023-06-07 13:20 UTC
Labels: ECR, Shipped
