### ISSUE TITLE
[ECR] [request]: Image replication from Docker Hub

### ISSUE THREAD

**Issue by toricls** [aws/containers-roadmap#714] opened 2020-01-22 06:24 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

We'd like to have an easy way to copy public images from Docker Hub to our own ECR repository when they got updated, so that we can isolate our container workloads and delivery pipelines from Docker Hub's failures (outage, missing images, and so on).

**Which service(s) is this request for?**
This could be Fargate, ECS, EKS, ECR

ECR

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

Similar things can be done right now by running third-party tools like https://github.com/seatgeek/docker-mirror or writing/operating a tool by ourselves but it would be great if we can use more _managed_ way to do.

**Are you currently working around this issue?**
How are you currently solving this problem?

Still in a consideration phase.

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by luhn** [comment] 2020-11-03 01:16
Duplicate of #939?  (Technically this issue predates it, but that issue seems to have picked up steam.)

**Comment by omieomye** [comment] 2020-11-03 18:38
We expect to offer this capability as part of #939, will mark this a duplicate and close. #939 has a broader title as customers want to leverage other upstream OCI-compliant 3rd party registries.

**Closed by omieomye** 2020-11-03 18:38 UTC
Labels: ECR, Proposed
