### ISSUE TITLE
[EKS] [request]: EKS Managed Nodes should allow attaching LB target groups

### ISSUE THREAD

**Issue by yann-soubeyrand** [aws/containers-roadmap#728] opened 2020-01-28 09:35 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

When creating an EKS managed node group, one should be able to set a list of LB target groups which the populated nodes would attach to. At the moment, one has to figure out which autoscaling group has been created for the managed node group and edit it to set the desired target groups. I guess this is an unsupported operation and that it could break if a new autoscaling group is created for the node group (node groups' resources.autoScalingGroups attribute being a list hints me that it could happen).

**Which service(s) is this request for?**

EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

We've a node group dedicated to ingress controllers which we'd like to attach to two target groups (http and https) which are the destination of the two listeners (tcp 80 and tcp 443) of our internet facing NLB.

**Are you currently working around this issue?**

At the moment, we manually edit the generated autoscaling group to attach the target groups, but we suspect this is a fragile setup and we can't rely on a fragile setup for such a critical part of our cluster.

**Additional context**

This request may be closely related to https://github.com/aws/containers-roadmap/issues/609.

**Comment by mikestef9** [comment] 2020-02-29 06:18
Closing as a duplicate of #709

**Closed by mikestef9** 2020-02-29 06:18 UTC
Labels: Proposed
