### ISSUE TITLE
ECS Service reaches steady state before container healthcheck pass

### ISSUE THREAD

**Issue by mailjunze** [aws/containers-roadmap#897] opened 2019-07-26 16:56 UTC
### Summary

ECS Service reaches steady state before container healthcheck pass.  This results in ECS update getting deployed via cloudformation successfully, However, the tasks go into restart loop after container health check fails rendering whole ECS service unstable. 

### Description

when we  perform an update via cloudformation to ECS. Cloudformation waits for "steady state" event to mark the update successful. "Service xxxxxxxx has reached a steady state." I can see the ECS service reaches the steady state and then the health checks fail, Which results cloud-formation deployment successfully but rendering  ECS service unstable. 

### Expected Behavior

ECS Service should reach  steady state after container healthcheck pass
### Observed Behavior
ECS Service reaches steady state before container healthcheck pass

**Comment by DireCorgi** [comment] 2020-09-16 20:10
We will be releasing a fix for this soon. With this change, all container health checks must be in a HEALTHY status before a Service or TaskSet can reach STEADY_STATE. This fix will apply to services using ECS/Rolling deployments controllers (Steady State event), external deployment controllers (TaskSet *stabilityStatus*) and CodeDeploy Blue/Green (deployments will now wait for Container Health Checks to pass before flipping traffic). Services not using container health checks will see no change in behavior. We will update this ticket once the change has been released.

**Comment by DireCorgi** [comment] 2020-10-02 19:15
The bugfix has been deployed in all regions. Feel free to reply or reopen this issue if the problem persists.

**Closed by DireCorgi** 2020-10-02 19:15 UTC
Labels: ECS

**Comment by kalpik** [comment] 2020-10-22 08:11
@DireCorgi does this fix only apply to stack updates? Because I am able to create an ECS service with a failing container health check via CloufFormation. Stack and Service are CREATE_COMPLETE, but the service just keeps restarting the container with the failing health check.

**Comment by emspoars** [comment] 2022-11-09 18:57
@kalpik it seems the issue is with Cloudformation now. The ECS service itself, as per the tests I ran today, does not reach a steady state anymore if the task health check fails.
