### ISSUE TITLE
[EKS] [kubelet/docker]: Change cgroup driver to systemd

### ISSUE THREAD

**Issue by saiteja313** [aws/containers-roadmap#1413] opened 2021-06-17 18:33 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
- Support cgroup driver configuration for Kubelet and Docker on EKS worker nodes

**Which service(s) is this request for?**
This could be Fargate, ECS, EKS, ECR
- EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

- Kubernetes documentation indicates that for stability reasons one should run kubernetes with the systemd cgroup driver if the init system itself is systemd.
- `awslabs/amazon-eks-ami` repository have a pull request thats been on hold due to downstream dependencies with eksctl.

https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cgroup-drivers

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by akestner** [comment] 2021-06-17 23:48
👋 @saiteja313! Can you help me understand the difference between this and #1210?

**Comment by stevehipwell** [comment] 2021-09-07 07:09
This issue is a duplicate of #1210.

**Comment by stevehipwell** [comment] 2023-02-07 17:31
FYI @dims

**Comment by dims** [comment] 2023-02-07 18:01
context for closing, please see:
https://github.com/aws/containers-roadmap/issues/1210#issuecomment-1421009424

**Closed by dims** 2023-02-07 18:01 UTC
Labels: EKS, Proposed
