### ISSUE TITLE
[EKS] Support for customer encrypted AMIs for EKS managed node group

### ISSUE THREAD

**Issue by vijaymateti** [aws/containers-roadmap#641] opened 2019-12-10 06:39 UTC
It would be great if you can provide the support to either use customer manager AMI KMS key or Encrypted AMIs for managed node groups in EKS. Our EC2 security policy doesn't allow unencrypted AMIs.

**Comment by mikestef9** [comment] 2020-08-17 19:58
Closing as duplicate of #665

**Closed by mikestef9** 2020-08-17 19:58 UTC
Labels: EKS, EKS Managed Nodes
