### ISSUE TITLE
[EKS] [request]: Add ability to set oidc options

### ISSUE THREAD

**Issue by jaxxstorm** [aws/containers-roadmap#166] opened 2019-02-15 14:43 UTC
**Tell us about your request**
Using IAM for authentication is not always the most desirable solution. I'd like to be able to specify server side configuration, specifically for oidc authentication

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
When interacting with EKS clusters from non Amazon resources, having to create and specify access keys and secret keys can be cumbersome. We do this a lot at $work and because we can't specify an oidc configuration for the API server, we end up having to build our own clusters.
Being able to set the following API flags on the api server:
- oidc-issuer-url
- oidc-client-id
- oidc-ca-file
- oidc-username-claim
- oidc-groups-claim

Would make this possible.

**Are you currently working around this issue?**
We are building our clusters using kubeadm :(

**Additional context**
This could be argued that it should be made possible to specify _any_ API server flags, but I'd like to keep the scope smaller now

**Comment by christopherhein** [comment] 2019-02-15 23:09
Thanks for submitting this. This is not currently on our roadmap. 

Can you help me understand more about you use case, would https://aws.amazon.com/blogs/opensource/integrating-ldap-ad-users-kubernetes-rbac-aws-iam-authenticator-project/ help to solve this?

It would give you the ability to use your AWS SSO to back your IAM roles which you could configure to use any LDAP/AD/SAML authentication mechanisms.

**Comment by jaxxstorm** [comment] 2019-02-16 05:16
This is possible yes, but when using tooling like Azure Active Directory, it add an additional layer of configuration.

Currently, as a user using oidc, I can:

- Assign the user to a group in Azure AD
- Map that group to a Kubernetes RBAC role

However, under the model you're proposing, I'd have to:

- Assign a user to a group in Azure AD
- *Map that user to an IAM role, presumably with role assumption*
- Map the IAM role to a Kubernetes RBAC role

This additional layer adds complexity for debugging purposes. For example - if a user has a permission issue, I have to track the issue down by checking their AD group, then checking their IAM role, then RBAC. It seems unnecessary to me to not just add the API server flag.

**Comment by lstoll** [comment] 2019-02-19 19:35
FWIW we ended up deploying an auth proxy to our clusters that authenticates users via OIDC, and then impersonates them to the API server. That allows us to manage access via our existing systems for users that may not have AWS access otherwise. The code is vaguely based on https://github.com/ericchiang/kube-oidc#kube-oidc-proxy

**Comment by christopherhein** [comment] 2019-02-19 19:39
> FWIW we ended up deploying an auth proxy to our clusters that authenticates users via OIDC, and then impersonates them to the API server. That allows us to manage access via our existing systems for users that may not have AWS access otherwise. The code is vaguely based on https://github.com/ericchiang/kube-oidc#kube-oidc-proxy

Sounds neat, is the code open source anywhere?

**Comment by jaxxstorm** [comment] 2019-02-19 20:16
@lstoll that sounds ideal - I would love some help/pointers. I really do think this should be reconsidered by AWS, so upvotes would be awesome if people want this feature

**Comment by sermilrod** [comment] 2019-02-22 15:43
I am also interested in this feature. The ability to configure identity providers is something we would like EKS to support. We need this because we want to map specific users to rbac rules so we have full and granular control over who has what access to kubernetes clusters without having to create an IAM user nor assume a role for it. This is particularly important in multi-tenant clusters

**Comment by universam1** [comment] 2019-03-05 08:30
> FWIW we ended up deploying an auth proxy to our clusters that authenticates users via OIDC, and then impersonates them to the API server. That allows us to manage access via our existing systems for users that may not have AWS access otherwise. 

We do the similar as well, but the OIDC integration in K8s is required still in order to map the JWT token into RBAC roles. For instance `Kubernetes Dashboard` needs that mapping to gain cluster level access.
@christopherhein this missing support is a surprise no-go for us in the effort moving to EKS!

**Comment by christopherhein** [comment] 2019-03-05 19:44
Thank you everyone for the feedback, really appreciate you talking about your use cases. Changing the label to `under consideration` 👍

**Comment by jaxxstorm** [comment] 2019-03-05 20:30
@christopherhein would it be easier to get this considered if we filed an issue which allows us to specify API server configuration in general, rather than specifically for oidc flags?

**Comment by christopherhein** [comment] 2019-03-05 20:54
> @christopherhein would it be easier to get this considered if we filed an issue which allows us to specify API server configuration in general, rather than specifically for oidc flags?

These more specific issues really help us to prioritize what is most important. The larger "enable all API flags configurable" are much harder given there is so many controls that _could_ introduce instability if improperly set if everything was customizable. Appreciate you putting this in and sharing the use cases.

**Comment by universam1** [comment] 2019-03-05 21:20
To second that point of only requesting this very feature for now - while it is rather simple to configure the oidc configuration it is completely indispensable regarding alternatives! 
IAM auth can be considered an option for tooling access but application level that is no alternative.
Is there an estimation possible @christopherhein ? Would be helpful for planning

**Comment by christopherhein** [comment] 2019-03-05 21:33
Estimation for this feature of adding OIDC flag capability @universam1 ? or are you talking about the Pod->IAM configuration #23 ?

**Comment by pammi22** [comment] 2019-03-06 00:40
@christopherhein is there any Estimation for this feature of adding OIDC flag capability?

**Comment by christopherhein** [comment] 2019-03-06 00:50
@pammi22 not as of now, we removed the `not-planned` label in favor of the `under consideration` while we consider how we would enable this customization with the control plane.

**Comment by whereisaaron** [comment] 2019-03-17 17:11
The lack of OIDC support for EKS is our single biggest issue for adoption. With stock k8s and dex we have a very clean, two-factor, federated single sign-on for clusters. These flags requested here would enable EKS clusters to have the same great user experience.

If EKS had built-in AWS Cognito support it is possible we could replace dex with Cognito for federating OIDC IDPs. But that support isn’t there currently AFAIK, and I can’t find any existing helper app that might bridge this gap in EKS. Anyone know of a project like this?

**Comment by aleks-mariusz** [comment] 2019-03-29 11:35
I would like to echo all the sentiments.. 

We use AD for corporate identity management, and to access AWS console we let the infra/admin group (only) use Okta which loads the console using a dedicated IAM role that grants full access.  It is unclear to me how setting up EKS with this assumed IAM role would affect having cluster-admin privs, but wanting to give end-users (sandbox'd) permissions to the kubernetes API server is very messy using EKS.

For contrast, what we currently have on-prem is AD -> federation via Keycloak -> which integrates with the k8s dashboard [via the proxy](https://github.com/int128/kubernetes-dashboard-proxy/) -> k8s dashboard.. and this allows end-users to log in with their AD creds cleanly, which works by mapping via JWT's provided by keycloak (which contain their AD group membership), that membership can then be mapped directly via RBAC rolebindings, to what roles they have (which control what access they have).   

It is such a clean and tight integration that it makes us want to consider skipping using EKS altogether and having a cloud-based kubernetes cluster by just managing the control plane ourselves.  I have yet to see what using EKS gets you over just rolling your own control plane if we don't have access to provide consistency (auth-wise) with what we have on-prem.  :-( Allowing us to add those 4 extra oidc related flags [ oidc-client-id /  oidc-issuer-url / oidc-username-claim / oidc-groups-claim ] would have us giving EKS more serious consideration for use.

**Comment by Spazzy757** [comment] 2019-04-25 06:30
Has there been an update to this issue? We are currently doing a POC for quite a large company to prove that they can move there on-prem clusters to EKS, however, they insist that they would need AD integration. Adding those flags could open up a much larger consumer base for EKS as it would allow migration from systems like AKS where the system is integrated into Azure Active Directory

**Comment by philwhln** [comment] 2019-04-25 16:37
We had to cancel our PoC of EKS because of this limitation.

**Comment by ccojocar** [comment] 2019-04-30 11:04
Any ETA for this feature? Thanks

**Comment by phanama** [comment] 2019-05-24 15:35
Any updates?
This limitation hesitates us from adopting EKS

**Comment by therealsamlin** [comment] 2019-06-07 03:25
OIDC is the single reason why we're using kops still instead of EKS. Just saying

**Comment by yuriipolishchuk-finsight** [comment] 2019-06-07 15:00
@therealsamlin take a look at https://github.com/jetstack/kube-oidc-proxy

**Comment by pvdvreede** [comment] 2019-06-07 22:36
@yuriipolishchuk-finsight that seems like an option for the future when its production ready. The only limitation is that because it uses impersonation to work it means that users of the cluster cannot take advantage of impersonation. We use impersonation to elevate our read only privileges to cluster admin so that would be something we would loose with that project.

Nice find though! 👍

**Comment by keattang** [comment] 2019-07-18 22:21
I created this auth proxy specifically for getting around this issue https://github.com/keattang/eks-auth-proxy/releases/new

**Comment by joshkurz** [comment] 2019-07-19 13:58
Here is a minimal solution that allows you to use oidc and eks. https://github.com/ww-tech/aws-sts-proxy/blob/master/examples/client/usage blog post about this setup is here https://medium.com/ww-tech-blog/amazon-eks-authentication-with-google-openid-connect-oidc-via-a-proxy-api-service-ebbf7913295c

**Comment by jirniy** [comment] 2019-08-21 19:17
is oidc options as eks api parameters in roapmap already there have any updates? it's really crucial and must-have option for EKS!

**Comment by olemarkus** [comment] 2019-09-21 07:54
It would be very useful with an update here now. If I undestand https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/ correctly, OIDC settings are now always set, but set to an AWS OIDC provider. And K8s does not support multiple providers https://github.com/kubernetes/kubernetes/issues/71162

**Comment by vitaly-am** [comment] 2019-09-21 12:09
just my little update, as per many weeks of researching, now l able to run AD integration via kube-oidc-proxy. long story short: kube-oidc-proxy make you able to use oidc in EKS and now you can get 2 scenarios for AD auth in AWS ASK 1)  gangway+dex+kube-oidc-proxy 2)kuberos+keycloak+kube-oidc-proxy

**Comment by omerfsen** [comment] 2019-12-09 13:18
+1

**Comment by wolfencom** [comment] 2019-12-10 15:25
Like many have said this was one of the biggest things that made us hesitate to use EKS here at Ticketmaster.

**Comment by posix4e** [comment] 2019-12-22 00:38
At our job we've started to call k8s clusters which don't allow for this feature as tier 2 since we can't put any secure workloads on them.

**Comment by kdwodc** [comment] 2020-01-13 16:14
+1 for us as well! PLEASE!

**Comment by dlippiatt** [comment] 2020-02-17 10:25
+1 here as well.

**Comment by mo-saeed** [comment] 2020-02-20 14:50
+1

**Comment by pakoAku** [comment] 2020-02-21 12:39
+1 would help us a lot

**Comment by vittoriocanilli** [comment] 2020-02-21 12:51
+1 that would help us in our project too!

**Comment by gtaylor** [comment] 2020-02-21 17:11
These +1 replies don't add to the conversation and generate quite a bit of spam. Could we use emojis on the original issue post instead?

**Comment by pierluigilenoci** [comment] 2020-02-24 10:04
On the other hand, generating noise shows an interest in this feature which would be a killer feature compared to the competitors.

**Comment by pierluigilenoci** [comment] 2020-02-24 10:12
Among other things, this feature would also solve several other problems with the integration of EKS with AWS SSO.

1) AWS SSO does not support API, Cloudformation or any kind of automation (it's impossible to automate the creation of Permission Set or Role) therefore in situations of complex granularity of access to the clusters it is hell to create/ manage/maintain.
2) AWS SSO doesn't even support nested groups in AAD.
3) Access to the dashboard with the token instead of with an OIDC proxy is much more complicated.

An external OIDC provider will solve all these issues.

**Comment by dlippiatt** [comment] 2020-02-25 10:51
I think its worth the extra noise to try and get it implemented. Its big break on adoption for some of us.

**Comment by shafi-khan** [comment] 2020-03-28 17:55
+1 for this feature.

**Comment by cmanzi** [comment] 2020-04-02 19:09
We require user-level auditing at the API server level (not possible with aws-iam-authenticator or any other equivalent API server proxy afaik), which is part of the reason why we are using Kops right now over EKS. Interestingly, we are actually using AWS Cognito as an OIDC provider for our clusters, and it works quite well. 

I'm curious as to why AWS hasn't offered native integration with Cognito User Pools - seems like a no-brainer. This feature would allow us to migrate our control planes to EKS in fairly short order.

**Comment by salamovz** [comment] 2020-04-06 10:11
I created LDAP authentication to eks cluster using this instructions
https://github.com/prydonius/dashboard-oidc-proxy

**Comment by dlippiatt** [comment] 2020-04-06 10:16
> I created LDAP authentication to eks cluster using this instructions
> https://github.com/prydonius/dashboard-oidc-proxy

@salamovz Did you get that to work on EKS? Did you have to make any changes?

**Comment by jlforester** [comment] 2020-04-06 14:26
I've been looking at kubelogin which needs two of these flags added to the apiserver

```--oidc-issuer-url=ISSUER_URL
--oidc-client-id=YOUR_CLIENT_ID```

**Comment by salamovz** [comment] 2020-04-07 11:10
Yes it perfectly work on EKS.
I changed gen-certs.sh to be:
`openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout server-key.pem -out server.pem -subj "/CN=kube-oidc-proxy.kube-oidc-proxy" -extensions SAN -config <(printf "[ req_distinguished_name ]\n[req]\ndistinguished_name  = req_distinguished_name\n[SAN]\nsubjectAltName='DNS.1:kube-oidc-proxy.kube-oidc-proxy'")`
But you can use any other tool to generate certificate.
In args inside of `kubectl -n kube-oidc-proxy edit deploy oidc-proxy-dashboard`
I added: `- --scopes=groups`
And when creating secrets please ensure you added '-n' to echo while creating base64 values like:
`echo -n "email" | base64`
And you DONT need to uncomment --apiserver-host `vi +125 dashboard/kubernetes-dashboard.yaml`

**Comment by enj** [comment] 2020-04-15 09:59
I have opened https://github.com/kubernetes/enhancements/pull/1689 as a provisional KEP to address this issue in a generic manner.

**Comment by abdellaui** [comment] 2020-06-02 19:17
Really necessary feature for production environments for avoiding unsupported work arounds😔

**Comment by pierluigilenoci** [comment] 2020-07-20 07:04
There is an open issue since one year for AWS SSO support on boto3. 
https://github.com/boto/boto3/issues/2091

**Comment by halcyondude** [comment] 2020-07-23 04:44
bump.  we're grappling with this presently.  Any update from the EKS team?

**Comment by Tokynet** [comment] 2020-08-24 14:26
...Bueller?
Any update or acknowledgment from AWS team would be appreciated.

**Comment by mhausenblas** [comment] 2020-08-24 14:52
> Any update or acknowledgment from AWS team would be appreciated.

I hear you. Lemme check back with the team and see if I can confirm something.

(PS: the 80s want their lines back ;)

**Comment by mikestef9** [comment] 2020-08-24 16:31
Hey all, just moved status to "coming soon". One important note here, is that EKS will only support issuer URLs with a publicly signed CA certificate, and oidc-ca-file will not be a supported flag.

**Comment by alex-berger** [comment] 2020-09-03 06:55
@mikestef9 Why is setting `oidc-ca-file` not supported, is there a technical reason or is it just not in scope for the first MVP? And which trust anchors (root CAs) will be used by the control plane to verify the oidc issuer's server certificate?

**Comment by d830061** [comment] 2020-11-07 07:48
Any news? Would like to start using this configuration as the current state via AWS SSO leads to undesired drifts when managing multiple cluster environments at scale.

**Comment by mercantiandrea** [comment] 2020-11-23 19:42
any news?

**Comment by yanivpaz** [comment] 2020-11-29 08:15
3 months in coming soon

**Comment by cdobbyn** [comment] 2020-12-07 18:02
It's not a high priority for them. They seemed pretty dismissive of it and suggested kube-oidc-proxy. It's pretty debilitating for administrators to have to link this to IAM. This becomes ultra complicated when you're managing multiple tenants on multiple clusters whom may need access to subsets of namespaces.

It sounds like the kind of priority that will keep getting shifted down to the bottom of the priority list.

**Comment by Morriz** [comment] 2021-02-05 23:33
I don't think AWS is interested in supporting other cloud users...out of the big cloud players, they seem to favor lock in the most...I am assuming they allow AWS Cognito via oidc?

**Comment by pierluigilenoci** [comment] 2021-02-08 10:18
@Morriz Cognito via OIDC is already working but it is annoying because every time you have to go through tokens with very short expiration and through the CLI. And you need to change the cluster config deeply to integrate with AAD groups. :(

**Comment by Morriz** [comment] 2021-02-08 12:19
@pierluigilenoci that is what I meant: they support their own (Cognito), but make it hard to use others (AAD).

**Comment by mikestef9** [comment] 2021-02-13 00:00
Hey everyone, happy to announce EKS now supports OIDC compatible identity providers as an additional user authentication option! The launch blog below walks through using Cognito as an example, but you can use any compatible OIDC provider as long the issuer URL is publicly available. 

- [What's New](https://aws.amazon.com/about-aws/whats-new/2021/02/amazon-eks-clusters-support-user-authentication-oidc-compatible-identity-providers/)
- [Launch Blog](https://aws.amazon.com/blogs/containers/introducing-oidc-identity-provider-authentication-amazon-eks/)
- [EKS Documentation](https://docs.aws.amazon.com/eks/latest/userguide/authenticate-oidc-identity-provider.html)
- [Kubernetes docs](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#openid-connect-tokens)

**Closed by mikestef9** 2021-02-13 00:00 UTC
Labels: EKS, Proposed

**Comment by Freyert** [comment] 2022-06-24 17:49
Does anyone have tips on troubleshooting this feature? The configuration is active, but when we submit a `kubectl` with a `--token` the audit log shows that the server did not populate the user field of the request.

The release blog shows the request should have a user field like so:

```
    "user": {
        "username": "test@example.com",
        "groups": [
            "gid:secret-reader",
            "system:authenticated"
        ]
    },
```

But our request always turn up like:

```
    "user": {
    },
```

And that's as far as I can get. I don't know of any other logs to look at to troubleshoot this issue.
