### ISSUE TITLE
[EKS] [addon]: Support Metrics Server in EKS addons

### ISSUE THREAD

**Issue by zsrinivas** [aws/containers-roadmap#1346] opened 2021-04-18 09:51 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Please add metrics server in EKS addons, preferably deployed over fargate.

**Which service(s) is this request for?**
This could be Fargate, EKS

**Are you currently working around this issue?**
we are self managing the metrics server deployment

**Comment by sjastis** [comment] 2023-07-31 00:02
Duplicate of https://github.com/aws/containers-roadmap/issues/261

**Closed by sjastis** 2023-07-31 00:02 UTC
Labels: EKS, Proposed, EKS Add-Ons
