### ISSUE TITLE
[EKS] [request]: make metrics configuration possible via API for NodeGroup

### ISSUE THREAD

**Issue by krzysztof-magosa** [aws/containers-roadmap#1849] opened 2022-10-03 15:46 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Please extend https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateNodegroup.html in a way allowing to configure enabled metrics, so https://github.com/hashicorp/terraform-provider-aws/issues/13793 can be resolved.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We want to have metrics for AutoScaling Groups created beneath Node Groups to be able to properly manage capacity over time.

**Are you currently working around this issue?**
We don't.

**Comment by mikestef9** [comment] 2022-10-03 16:30
Closing as duplicate of #762

**Closed by mikestef9** 2022-10-03 16:30 UTC
Labels: Duplicate / Merged
