### ISSUE TITLE
[EKS] [request]: Support EKS with Custom Cluster Domain

### ISSUE THREAD

**Issue by venky999** [aws/containers-roadmap#1136] opened 2020-11-05 10:44 UTC
**Community Note**
Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment
Tell us about your request
**What do you want us to build?**
Start EKS with Custom Cluster Domain
**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Support to start EKS with a custom cluster domain instead of (cluster.local) to something like myaccountname.mydomain.com so that we can create PKI certs specific to that domain and other k8s clusters in other accounts have different domain and the certs cannot have same SANs.
So that someone cannot use the cert retrieved from one cluster on another.

**Are you currently working around this issue?**
NONE. Taken risk and Issuing certs for *.SVC.CLUSTER.LOCAL

**Comment by k4kratik** [comment] 2023-07-10 07:18
any updates on this?

**Comment by k4kratik** [comment] 2023-09-26 12:23
Finally found a solution that works for me : 
1. Create a Launch Template for EKS nodes, Add additional kubelet-args in user data script : 
```
#!/bin/bash
set -ex
/etc/eks/bootstrap.sh test --kubelet-extra-args "--cluster-domain=myaccountname.mydomain"
```
2. Edit the Config Map of CoreDNS 
```
kubectl edit -n kube-system cm coredns
```
3. and Replace cluster.local with my `myaccountname.mydomain`
4. restart CoreDNS pods
```
kubectl rollout restart deployment -n kube-system coredns 
```

Test : 
```
kubectl get --raw "/api/v1/nodes/NODE_NAME/proxy/configz" | jq | grep -i domain
```

![image](https://github.com/aws/containers-roadmap/assets/20947380/5b759fb5-2de8-4029-999a-38092f0f73e3)

**Comment by silentrangerr** [comment] 2023-12-08 18:29
Hi, where do we exactly get the  NODE_NAME from?

**Comment by mikestef9** [comment] 2024-04-11 22:19
Closing as duplicate of #283

**Closed by mikestef9** 2024-04-11 22:19 UTC
Labels: EKS, Proposed

**Comment by Moulick** [comment] 2024-10-03 14:37
> Hi, where do we exactly get the NODE_NAME from?

`kubectl get nodes`
