### ISSUE TITLE
[eks] [request]: Enable OIDC option when create the cluster

### ISSUE THREAD

**Issue by maradwan** [aws/containers-roadmap#1730] opened 2022-04-29 15:06 UTC
To use IAM roles for service accounts in your cluster, you must create an IAM OIDC Identity Provider. 
It will be easier if you add an option on UI and API that users can enable/disable OIDC when creating an eks cluster.

**Comment by maradwan** [comment] 2022-07-07 22:03
I have used Lambda to automate the OIDC creation, see my article
https://dev.to/aws-builders/using-lambda-to-automate-oidc-and-iam-role-for-service-account-in-eks-c0e

**Comment by clouddev-code** [comment] 2022-09-03 11:53
can enable OIDC provider  by eksctl withOIDC
https://eksctl.io/usage/schema/

**Comment by mikestef9** [comment] 2024-04-12 00:34
Closing as duplicate of #1233

**Closed by mikestef9** 2024-04-12 00:34 UTC
Labels: EKS, Proposed
