### ISSUE TITLE
[Fargate] [request]: allow more than one pod per node

### ISSUE THREAD

**Issue by adamwilner** [aws/containers-roadmap#1265] opened 2021-02-09 22:36 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
At the moment Fargate limits to one pod per node. This makes things like daemonsets impossible and forces us to to use more nodes than we need. It would be a big improvement to allow for assigning multiple pods to nodes based off need and available resources like GCP does in their managed node offering. 

**Which service(s) is this request for?**
Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I can't use daemonsets. I need to pay for two nodes to run two pods when they could both fit on one node. 

**Are you currently working around this issue?**
I am required to do hacky things with sidecars when daemonsets would be an easier and more elegant solution. 

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by mreferre** [comment] 2021-02-11 09:39
Thanks @adamwilner for your request. I'd like to understand better the requirement. Fargate has a few key tenets that it would be hard to tweak to fit into this request (e.g. 1 pod per compute environment). In general a better way to think of Fargate is that there is no need to think about nodes/servers/infrastructure instead of trying to optimize it. Actually the reason why we have to show worker nodes in EKS/Fargate is mostly because that's how Kubernetes works not because there is a need to show the node configuration (or that the node ever exists for that matter).  

Having that said, the Daemonset question is fair. Our goal is to try to hide/manage as much as possible of modules you need to deploy with DS. [Firelens for EKS/Fargate](https://aws.amazon.com/blogs/containers/how-to-capture-application-logs-when-using-amazon-eks-on-aws-fargate/) is a good example of this in that we manage fluentbit for you as part of the Fargate stack and you only configure your logging endpoint (no need for sidecars etc). We do realise there are other needs for DS/sidecars. Would you mind sharing what you specific need is? What would you need to run as a DS/sidecar?    

I fear the question/requested related to optimizing the node size comes from a misunderstanding. When you deploy a pod we right size the compute environment for the pod requests. You may be misled by looking at the size of the worker node. That is not relevant. You are NOT paying for that capacity. See here for more background: https://github.com/aws/containers-roadmap/issues/1248 

Note there may be situations where you need standard worker nodes because you have specific DS you need to run, or because you need to use specific features only available (for now) on EC2 (e.g. GPU) or simply because the way you run your workloads may benefit more from your fine tune of the resources in the cluster (very hard to do). In this case your best option would be to leverage [EKS managed node groups](https://docs.aws.amazon.com/eks/latest/userguide/managed-node-groups.html). EKS Managed node groups appear to be a better apple-to-apple comparison to how other cloud providers try to mitigate the burden of managing infrastructure.

**Comment by omieomye** [comment] 2022-03-30 06:27
@adamwilner I'm going to close this as a duplicate of https://github.com/aws/containers-roadmap/issues/971, given that your ask mentions daemonsets as the reason for multiple EKS pods per 'Fargate node'. Let me know if this is incorrect.

**Closed by omieomye** 2022-03-30 06:27 UTC
Labels: EKS, Fargate, Proposed

**Comment by chkp-alexgl** [comment] 2022-11-27 17:06
> Actually the reason why we have to show worker nodes in EKS/Fargate is mostly because that's how Kubernetes works not because there is a need to show the node configuration (or that the node ever exists for that matter)

@mreferre I am curious whether it has been considered to model the entire fargate profile as a single k8s node?

**Comment by mreferre** [comment] 2022-11-28 17:36
@chkp-alexgl indeed it was. We explored the virtual Kubelet back than (see [the blog](https://aws.amazon.com/blogs/opensource/aws-fargate-virtual-kubelet/)) but we determined that that model did not meet our requirements for reliability, security and scalability design. Also, virtual Kubelet (or any such approach) is a fork of the upstream Kubernetes project and we did not want to go down that route (one of our EKS tenets is to use Kubernetes upstream). We decided to use a more "by the book" approach using mutating web-hooks and a custom scheduler.
