### ISSUE TITLE
[EKS] [request]: EKS Support in Cape Town, South Africa DataCenter (af-south1)

### ISSUE THREAD

**Issue by connor-cress** [aws/containers-roadmap#927] opened 2020-06-01 00:54 UTC
**

### Community **Note**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
-_Support for EKS in the Cape Town, South Africa DataCenter_

**Which service(s) is this request for?**
This could be Fargate, ECS, EKS, ECR
- _EKS_

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.
-_I am trying to improve Latency for my company, but we need EKS Support. I was wondering if that could become a Proposed Issue._

**Are you currently working around this issue?**
How are you currently solving this problem?
-_By waiting._

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by TRCEReaper** [comment] 2020-06-01 09:45
Do you work for AWS

**Comment by JarydC** [comment] 2020-06-04 08:26
when will eks be finished in SA

**Comment by Anonymous263-Anonymous** [comment] 2020-06-09 08:08
when will it be done

**Comment by jojo786** [comment] 2020-08-07 05:04
https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-eks-now-available-cape-town-milan/

**Comment by mikestef9** [comment] 2020-08-07 13:51
Closed as duplicate of #848

**Closed by mikestef9** 2020-08-07 13:51 UTC
Labels: Proposed
