### ISSUE TITLE
[EKS] [Request]: VPC private link or Endpoint service for private EKS server api.

### ISSUE THREAD

**Issue by GowthamChinta** [aws/containers-roadmap#1804] opened 2022-08-12 07:44 UTC
Service: EKS

I would like to create a private communication from ArgoCD application running in EKS cluster (us-east-1) to EKS API server (ap-east-1). This is to establish communication from ArgoCD to the EKS cluster running in another account and another region so ArgoCD can install the application set configured. 

I dont want to use VPC peering across these regions since VPC peering requires to open a subnet range communication which exposes applications inside EKS as well. I want to configure this without VPC peering. 

I have gone through AWS private link which creates a communication to applications inside EKS service through a NLB. but my requirement is to connect to EKS API server endpoint itself which is in private  without VPC peering.

**Comment by mikestef9** [comment] 2022-09-01 22:29
Closing as duplicate of #1171

**Closed by mikestef9** 2022-09-01 22:29 UTC
Labels: EKS, Duplicate / Merged
