### ISSUE TITLE
[EKS] [request]: Support cluster-autoscaler during managed nodegroup updates

### ISSUE THREAD

**Issue by nothingofuse** [aws/containers-roadmap#916] opened 2020-05-27 17:13 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

The request is to add new nodes with this annotation:
```"cluster-autoscaler.kubernetes.io/scale-down-disabled": "true"```
so that they will not be scaled down during the process, causing the entire update to fail. see more info here: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-prevent-cluster-autoscaler-from-scaling-down-a-particular-node

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently, managed nodegroup updates fail consistently in clusters with cluster-autoscaler deployed.  This is due to the amount of time it takes the process to begin shifting workloads to the new nodes.
This annotation on upcoming nodes during the process should resolve the issues around cluster-autoscaler fighting the nodegroup update process.

**Are you currently working around this issue?**
Currently the workaround are to delete the cluster-autoscaler deployment from the cluster prior to the nodegroup update, and reapply it afterwards; or use the ```scale-down-delay-after-add``` flag on the deployment to set a (long) delay of around 60-75 minutes

**Additional context**
Error in the nodegroup update console will look like:
```
NodeCreationFailure | Couldn't proceed with upgrade process as new nodes are not joining node group NODEGROUPNAME

```

**Comment by ellistarn** [comment] 2020-08-12 23:40
Great find!
From my initial read on this, I see three solutions here.

1. Managed Node Groups could be tolerant to its nodes disappearing during an upgrade. For example, from how you've described this issue, node upgrade could also fail if you manually reduce the size of your ASG during upgrade.
2. Managed Node Groups could apply the label `"cluster-autoscaler.kubernetes.io/scale-down-disabled": "true"` while upgrading, as you suggest, to prevent cluster autoscaler from interrupting it.
3. Managed Node Groups could use instance termination protection on nodes while upgrading.

In the short term, we recommend disabling the Cluster Autoscaler while upgrading Managed Node Groups.

**Comment by dcherman** [comment] 2020-10-09 18:48
As another alternative, you can disable cluster-autoscaler on the specific nodegroup entirely during managed nodegroup operations.  I do that myself in an upgrade controller that I wrote to support this use case:

* Delete the `k8s.io/cluster-autoscaler/enabled` tag from the underlying ASG
* Sleep for 75s ( cluster-autoscaler has a 1 minute hard-coded refresh interval )
* Trigger the nodegroup upgrade
* Re-add the `k8s.io/cluster-autoscaler/enabled` tag
* Sleep for 75s again to ensure that it's available for use by cluster-autoscaler again
* Rinse and repeat with the next nodegroup until finished

**Comment by Jelle7** [comment] 2020-10-13 16:16
I had the same issue, however it was not caused by the autoscaler tag/deployment. I managed to fix it by updating the Amazon VPC CNI plugin to the latest version:

https://docs.aws.amazon.com/eks/latest/userguide/cni-upgrades.html

**Comment by halfinhalfout** [comment] 2020-10-13 18:35
I also had the same issue, which was resolved by upgrading the version of the CNI Plugin for EKS. 

We were running CNI v1.5.3, with EKS backplane v1.16. When we upgraded to CNI v1.7.5, it resolved the issue.

https://docs.aws.amazon.com/eks/latest/userguide/cni-upgrades.html

**Comment by esanchezm** [comment] 2020-11-03 11:40
I'm also affected by this (or something similar). We're trying to upgrade a managed node group that uses a Launch Template with the sole purpose of tainting the nodes using the userdata bootstrap script. I was trying to upgrade that script because I realised it wasn't working properly. Now bootstrap works, I can see the nodes joining the cluster and scheduling pods, but EKS decides they're not OK and the rollout fails.

I've updated CNI from 1.6.1 to 1.7.5, scaled cluster-autoscaler to 0, but still getting the same error in the EKS console:

```
NodeCreationFailure | Couldn't proceed with upgrade process as new nodes are not joining node group NODEGROUPNAME
```

**Comment by suket22** [comment] 2021-01-06 17:38
Hello, 

  We’ve made a change to resolve this issue. You should now be able to leave ClusterAutoscaler running when updating your nodegroup via the UpdateNodegroupVersion API. 
  
  While the Nodegroup update is in progress, any new node being launched will be annotated with `"cluster-autoscaler.kubernetes.io/scale-down-disabled": "true”` which protects against ClusterAutoscaler scaling it back down.   When the Nodegroup update process is completed, the annotation will be removed from all nodes in the node group.

**Closed** 2021-01-06 17:40 UTC
Labels: EKS, EKS Managed Nodes, Proposed

**Comment by 64bit** [comment] 2022-03-21 22:03
It would be nice to include the fact that managed nodegroup upgrade adds annotation `"cluster-autoscaler.kubernetes.io/scale-down-disabled": "true”`  in this guide for future EKS users: 

https://docs.aws.amazon.com/eks/latest/userguide/managed-node-update-behavior.html
