### ISSUE TITLE
[EKS]: Possibility to create EKS cluster without anything preinstalled

### ISSUE THREAD

**Issue by stijndehaes** [aws/containers-roadmap#496] opened 2019-09-24 13:18 UTC
**Tell us about your request**
I want to have the possibility do launch an EKS cluster without the CNI, kube-proxy daemonset and core-dns deployment on it. 

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

We use terraform to manage our infrastructure as code, terraform struggles to create resources that already exist on kubernetes, so we have a manual step to delete those. Or we have to manually manage those resources. We would like to have a clean EKS cluster so we can install these ourselves.

**Are you currently working around this issue?**
At the moment we manage this manually according to the docs: https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html

**Additional context**
no

**Attachments**
none

**Comment by mikestef9** [comment] 2023-01-08 04:30
Closing as duplicate of #923

**Closed by mikestef9** 2023-01-08 04:30 UTC
Labels: EKS, Proposed
