### ISSUE TITLE
[Fargate] [request]: Expose HEALTHCHECK logs

### ISSUE THREAD

**Issue by jamesskinner** [aws/containers-roadmap#1121] opened 2020-10-16 10:22 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Expose container healthcheck logs

**Which service(s) is this request for?**
Fargate

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We are spending quite some time trying to debug container healthchecks that are failing for an unknown reason. Apart from container logs and the fact the healthcheck passed or failed we have nothing to help debug the issue.

Docker stores stdout and stderr output from the healthcheck commands and exposes it via `docker inspect`. It would be very useful if we could access this output somehow so we can debug the healthchecking command.

**Are you currently working around this issue?**
We have not implemented any workaround but I would try and wrap the command, capture the output and dump the logs somewhere externally

**Comment by Kreinoee** [comment] 2020-10-27 09:51
This once seems to be a duplicate of #1114 

But I think this one has a more desciptive subject.

**Comment by jamesskinner** [comment] 2020-11-01 17:17
Good point, didn't see the other one. Closed this.

**Closed** 2020-11-01 17:17 UTC
Labels: Fargate, Proposed
