### ISSUE TITLE
[EKS] [request]: Speed up associating and disassociating the identity provider to EKS cluster

### ISSUE THREAD

**Issue by bseenu** [aws/containers-roadmap#1438] opened 2021-07-15 10:36 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
```
aws_eks_identity_provider_config.eks_identity_provider_config: Still creating... [23m20s elapsed]
aws_eks_identity_provider_config.eks_identity_provider_config: Still creating... [23m30s elapsed]
aws_eks_identity_provider_config.eks_identity_provider_config: Still creating... [23m40s elapsed]
aws_eks_identity_provider_config.eks_identity_provider_config: Still creating... [23m50s elapsed]
aws_eks_identity_provider_config.eks_identity_provider_config: Still creating... [24m0s elapsed]
aws_eks_identity_provider_config.eks_identity_provider_config: Still creating... [24m10s elapsed]
aws_eks_identity_provider_config.eks_identity_provider_config: Still creating... [24m20s elapsed]
aws_eks_identity_provider_config.eks_identity_provider_config: Still creating... [24m30s elapsed]
aws_eks_identity_provider_config.eks_identity_provider_config: Still creating... [24m40s elapsed]
aws_eks_identity_provider_config.eks_identity_provider_config: Still creating... [24m50s elapsed]
╷
│ Error: error waiting for EKS Identity Provider Config (sboga-test2:azure) association: context deadline exceeded
│
│   with aws_eks_identity_provider_config.eks_identity_provider_config,
│   on oidc.tf line 1, in resource "aws_eks_identity_provider_config" "eks_identity_provider_config":
│    1: resource "aws_eks_identity_provider_config" "eks_identity_provider_config" {
│
╵
```
I believe this is because of the need to restart api server, can we optimize this and make it bit better

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
improve the overall time to bring up and tear down the eks cluster

**Comment by haarchri** [comment] 2021-12-09 20:41
we associate the OIDC via crossplane with compositions - problem here is that the whole time (25-60 min) when OIDC is configured the controlplane is in status updating - an additional status code for oidc configuration would be helpful

**Comment by orangenagy** [comment] 2022-01-06 11:43
We use identity provider as part of our standard build for EKS clusters. The problem here is - aside from the annoyance of adding ~1 hour to cluster build time, it makes things such as spin up / down cluster as part of automated tests so long that it's impractical.

**Comment by timblaktu** [comment] 2022-03-30 00:10
+1 what @orangenagy said.

**Comment by timblaktu** [comment] 2022-03-30 00:48
I'm getting errors trying to specify a timeout block [as documented](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_identity_provider_config#timeouts):

```
│ Error: Unsupported block type
│ 
│   on okta.tf line 19, in resource "aws_eks_identity_provider_config" "okta":
│   19:     timeouts {
│ 
│ Blocks of type "timeouts" are not expected here.
```

Is this not supported or is my syntax wrong:

```
resource "aws_eks_identity_provider_config" "okta" {
  cluster_name = module.eks.cluster_id

  oidc {
    client_id = "*****"
    # This appears in this cluster's list of identity providers, so doesn't need differentiation
    identity_provider_config_name = "okta"
    issuer_url                    = "*****"
    # As described here: https://developer.okta.com/blog/2021/10/08/secure-access-to-aws-eks#add-okta-as-an-oidc-provider-on-your-eks-cluster
    # We must use the following values for Okta integration.
    username_claim = "email"
    groups_claim   = "groups"
    # Resource creation takes about 30 minutes, but destroy/disassociation sometimes times out at 40 minutes.
    # The Create/Destroy timeouts each default to 40 minutes:
    #   https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_identity_provider_config#timeouts
    timeouts {
      create = "60m"
      delete = "60m"
    }
  }
}
```

WE're using provider version:

```
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.7.0"
    }
```

**Comment by sam19111** [comment] 2022-05-04 19:54
@timblaktu I get the following error when dissociating EKS Identity Provider.
```
│ Error: error disassociating EKS Identity Provider Config (devops-wheel-prototype-sam:okta): InvalidRequestException: Provided subnets subnet-0b0b5c97e8ded855b Free IPs: 0 , need at least 5 IPs in each subnet to be free for this operation
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "8afd2264-1c90-42be-a093-bebda5d2e390"
│   },
│   Message_: "Provided subnets subnet-0b0b5c97e8ded855b Free IPs: 0 , need at least 5 IPs in each subnet to be free for this operation"
│ }
│
│
╵
╷
│ Error: context deadline exceeded
│
│
```
What can be done in this case? We got a situation where the IPs have been gobbled up earlier today?

**Comment by nitrocode** [comment] 2022-06-17 19:05
It took me ~32 minutes to destroy it.

**Comment by maximmold** [comment] 2022-06-18 04:40
Could there be a way to associate during the initial cluster build out? It seems like that would reduce the overall time instead of a separate operation post cluster creation.

**Comment by tracetechnical** [comment] 2022-07-07 21:55
This is still a _big_ problem. Taking ~30 mins each way.

**Comment by zensqlmonitor** [comment] 2022-08-04 07:31
Same issue for me. Taking ~30 mins each way.

**Comment by timblaktu** [comment] 2022-09-08 22:07
All, what's the latest understanding of root cause for this long-running process? Has anyone obtained any insight here? I'm considering using another EKS-OIDC-RBAC solution in another Enterprise environment, and wanting to know what to expect in terms of bloated deployment time. I see from the recent comments and Open status that it's still a major problem..

Has anyone looked in a verbose CloudTrail for breadcrumbs indicating what's actually going on under the hood when the `eks_identity_provider_config` is `Still creating...`?

Since the configuration of each "client application" at the OIDC provider-side typically includes filters that limit the users and groups that the application cares about, one would think that there is not very much data that has to be transferred in this transaction between OIDC Provider and EKS control plane. If CloudTrail doesn't shine any light, perhaps we need a refresher on the [OIDC Specs and Guides](https://openid.net/connect/) (or in my case, to learn it for the first time..).

@haarchri any updates on how this works/behaves using your Crossplane composition? This is one of the IaC approaches I'm now taking for EKS clusters, and am just wondering what I can learn from the trailblazers before me. ;-)

**Comment by mikestef9** [comment] 2023-02-09 23:58
We are continually working to improve speed of updates but going to close this issue as associating/disassociating identity providers is now under 10 minutes per cluster. You can more find more details here https://aws.amazon.com/blogs/containers/amazon-eks-control-plane-auto-scaling-enhancements-improve-speed-by-4x/.

**Closed by mikestef9** 2023-02-09 23:58 UTC
Labels: EKS, Proposed

**Comment by tracetechnical** [comment] 2023-02-10 09:53
Under 10m is still unacceptable. No wonder people go to Azure for a competent K8S offering

**Comment by kdomanski** [comment] 2023-02-13 10:30
Hey AWS, looks like your API currently doesn't allow creating an EKS cluster with OIDC configuration already in it. This delay seems to be caused by the `associate-iam-oidc-provider` de-provisioning and re-provisioning the control plane.

The usability issue would be solved for 95+% usecases if you'd extend the `create-cluster` call and allow setting up OIDC from the get-go.

**Comment by n3ph** [comment] 2023-08-22 12:20
Furthermore, only a single OIDC configuration is supported currently. 🤦🏼
