### ISSUE TITLE
New EKS region: Canada

### ISSUE THREAD

**Issue by dave-anand** [aws/containers-roadmap#63] opened 2018-12-14 03:23 UTC
It'd be great to have EKS in ca-central-1.

**Comment by MarkFreebairn** [comment] 2018-12-20 15:32
This would be especially good for me as I am currently using kops in Canada but as it only has 2 AZs it makes running masters highly available very difficult

**Comment by mbelang** [comment] 2018-12-21 16:38
Yup that would be great to have it in Canada...

**Comment by tabern** [comment] 2019-01-16 18:04
Duplicate of #113

**Closed by tabern** 2019-01-16 18:04 UTC
Labels: EKS, Proposed
