### ISSUE TITLE
 [EKS] [request] Have a notificaton about EKS platform upgrade

### ISSUE THREAD

**Issue by yws-ss** [aws/containers-roadmap#1498] opened 2021-09-10 07:03 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Currently, the EKS platform upgrade don't have any notification. We want to have some notification when the platform upgrade through the e-mail or Personal Health dashboard.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
The platform upgrade sometime will affect the connection between API server and application. We have implemented the retry mechanism, but still want to have an notification when EKS team plan to upgrade the platform version.

**Comment by mikestef9** [comment] 2021-09-10 13:47
Closing as duplicate of #604

**Closed by mikestef9** 2021-09-10 13:47 UTC
Labels: EKS, Proposed, Duplicate / Merged
