### ISSUE TITLE
[VPC-CNI] [request]: Support Layer7 network policies

### ISSUE THREAD

**Issue by ferrandinand** [aws/containers-roadmap#2303] opened 2024-03-07 11:22 UTC
We are adopting vpc-cni as our stantdard cni in our clusters and using it also to work with our network policies but we have been required now to filter traffic by DNS hostnames with L7 rules.
This is possible with Calico Enterprise and Cillium but seems an architectural challenge in vpc-cni.

Cillium also has a long open issue to work along with vpc-cni L7 with many challenges.
https://github.com/cilium/cilium/issues/12454

**Comment by mikestef9** [comment] 2024-12-20 22:19
Closing as duplicate of #2180

**Closed by mikestef9** 2024-12-20 22:19 UTC
Labels: EKS, Proposed, EKS Networking
