### ISSUE TITLE
[EKS] [addon]: Support ArgoCD in EKS addons

### ISSUE THREAD

**Issue by phajduk** [aws/containers-roadmap#1704] opened 2022-04-08 12:30 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
In similar fashion to https://github.com/aws/containers-roadmap/issues/1593 I would like to propose implementing EKS add-on for [ArgoCD](https://github.com/argoproj/argo-cd). ArgoCD has 3 times more stars in Github than FluxV2 so there's no reason to skip this excellent piece of open-sourced solution. 

**Which service(s) is this request for?**
EKS.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
ArgoCD team made a lot of effort to make ArgoCD a fully integrated solution that can deploy Kubernetes workflows reliably. After decisions similar to [this](https://github.com/argoproj-labs/argocd-notifications/commit/18892b78d753c07c1b21a5bc107d261ae4fd6319) it seems like ArgoCD has become a battery-included solution (excellent UI, notifications etc.).

**Are you currently working around this issue?**
Kubernetes provider in Terraform or via Helm chart.

**Additional context**
Launching EKS with such an add-on can help deploy a lot of other resources almost immediately. For example, we launch EKS cluster, enable addon like ArgoCD, then we apply ArgoCD configuration via `kubectl apply -f ...` and we're ready in minutes with our cluster. No additional CLI tools are required.

**Comment by mikestef9** [comment] 2022-04-08 15:48
Closing as duplicate of #1176

**Closed by mikestef9** 2022-04-08 15:48 UTC
Labels: Proposed
