### ISSUE TITLE
Daemon Service launch guarantee

### ISSUE THREAD

**Issue by zsrinivas** [aws/containers-roadmap#668] opened 2019-12-27 15:11 UTC
### Description
Daemon Service task launch is not always guaranteed, i.e when a significant number of ec2 instances are replaced in an ECS cluster. ECS can place the normal service tasks on the ec2 instance and consume all the memory/CPU up to a point where the daemon service task can't be launched.

Daemon Services like filebeat etc,.. are very critical to be launched on the instances and there should be guarantees that they will be launched.

**Comment by efenderbosch** [comment] 2020-01-03 16:43
Seconding this. The EC2 instance should not be available for REPLICA tasks until all DAEMON tasks have started and are HEALTHY. Maybe a DAEMON task level flag?

**Comment by coultn** [comment] 2020-01-07 17:57
This is a duplicate of #428

**Closed by coultn** 2020-01-07 17:57 UTC
Labels: ECS, Proposed
