### ISSUE TITLE
[EKS] [Capacity Type]: Allow Managed Node Groups to specify percentage of Spot/On-Demand Capacity

### ISSUE THREAD

**Issue by igaskin** [aws/containers-roadmap#1561] opened 2021-11-18 00:13 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Allow Managed Node Groups (MNG) to specify a percentage of Spot vs On-Demand instances.  Autoscaling groups (ASG) already support the ability to specify a percentage of spot instances vs on-demand instances, it would be nice to optionally expose this level of customization at the MNG level.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We would like to run a blend of spot and on-demand instances for our MNG, for the reasons of cost savings, but to have the confidence that we will always have a minimum number of instances running.

**Are you currently working around this issue?**
Creating a copy of the MNG, and change the Capacity Type.  Manually set min/max/desired values to achieved the desired percentage of spot instances.

**Additional context**
Manually editing the percentages of the ASG will be reverted by the MNG, so it is not feasible to do some "post processing" of the ASG after the MNG is created.

**Comment by jicowan** [comment] 2021-11-18 16:15
@igaskin can you explain how you envision this working? Today, all of the nodes within a managed node group as assigned the same set of labels and taints. If there were a mechanism to adjust the mix of spot and on-demand instances within a node group, how would you target workloads to only run on spot instances within that node group? Ordinarily you would use node labels or taints/tolerations, but if they're all the same, how will the scheduler be able to differentiate between spot and on-demand?

**Comment by igaskin** [comment] 2021-11-18 17:41
@jicowan that's a good point.  For me its not a hard requirement to be able to distinguish between on-demand and spot within the same node pool.  Workloads that require a higher level of permanence, we simply run on a separate node pool that is 100% on-demand.

Two possible options for solving the assignment of taints for spot nodes could be:
* in user-data query ec2-instance id, and check if that instande-id is returned in `ec2 describe-spot-instance-requests`
* transparently create 2 separate ASGs and dynamically update min/max/desired counts to match the users preference of percentage.

**Comment by mikestef9** [comment] 2021-11-18 18:24
Closing as duplicate of #1297, can move the discussion there

**Closed by mikestef9** 2021-11-18 18:24 UTC
Labels: EKS, Proposed, EKS Managed Nodes
