### ISSUE TITLE
[EKS] [ArgoCD]: Please Provide ArgoCD (GitOps) tool as Add-on Feature in Amazon EKS 

### ISSUE THREAD

**Issue by malikdraz** [aws/containers-roadmap#1820] opened 2022-08-26 13:46 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

Please provide a native solution to deploy ArgoCd (GitOps) tool as an Amazon EKS add-on like we currently have kube-proxy, amazon-vpc-cni plugins etc. 

**Which service(s) is this request for?**
Elastic Kubernetes Service (EKS)

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

ArgoCD is a GitOps solution that is becoming more and more popular. Currently, there is no native solution to deploy AargoCD. 

**Are you currently working around this issue?**
How are you currently solving this problem?

We are currently deploying this using a manual YAML file provided by ArgoCD documentation. 

**Additional context**
Anything else we should know?

ArgoCD (GitOps) is going to be more and more popular in the upcoming months and years since they do solve a major problem in the world of deployment (CICD) with Kubernetes. Further, ArgoCD is incubating the CNCF project, which is currently being used widely in the industry. This will be a great initiative from the Amazon EKS team to provide more value to customers.

**Comment by mikestef9** [comment] 2022-08-29 04:00
Closing as duplicate of #1176

**Closed by mikestef9** 2022-08-29 04:00 UTC
Labels: EKS, Duplicate / Merged
