### ISSUE TITLE
[EKS] [question]: CoreDNS addon installation required?

### ISSUE THREAD

**Issue by FernandoMiguel** [aws/containers-roadmap#1687] opened 2022-03-23 11:19 UTC
I'm looking more for clarification than reporting an issue.
When deploying an EKS cluster, kube-proxy, coredns and VPC CNI plugins are automatically deployed.
The cluster **also** provides the option to install addons in its own tab
![image](https://user-images.githubusercontent.com/168366/159687009-efdba3d8-6d64-46aa-8a4a-4b0f4680ddb8.png)

1. Why are these two different processes?
2. Do both guarantee the same version to be installed / upgraded?

**Which service(s) is this request for?**
EKS

**Are you currently working around this issue?**
When deploying a fargate-only cluster and install the coredns addon, the installation stucks.
This happens cause there are workloads created for the addons the moment the cluster is created, before the addons are even installed.
Since for some reason I don't really have context for, the coredns deployment is only made to work on ec2, and needs to be patched to run on fargate (https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html#fargate-gs-coredns).
This requires our automation to patch the deployment and only then install coredns addon.

3. Are the addons even required to be installed, if they are already deployed on cluster creation?

**Comment by bryantbiggs** [comment] 2022-03-23 11:31
Ref: https://github.com/aws/containers-roadmap/issues/923

**Comment by miroljub1995** [comment] 2022-06-16 16:06
Is there a good reason why this annotation is set to ec2 and not left blank to support both EC2 and Fargate?

**Comment by mikestef9** [comment] 2022-12-06 00:20
Closing as duplicate of #944. With coming soon launch of add-ons configuration support, you'll be able to pass computeType through the API to work with Fargate out of the box.

**Closed by mikestef9** 2022-12-06 00:20 UTC
Labels: EKS, Proposed, EKS Add-Ons
