### ISSUE TITLE
[EKS] [request]: Use /ready instead of /health on readiness probe of CoreDNS

### ISSUE THREAD

**Issue by ueokande** [aws/containers-roadmap#941] opened 2020-06-11 23:29 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

AWS EKS should use `/ready` instead of `/health` to observe the readiness of CoreDNS pods.

The current manifest (provided from https://amazon-eks.s3.us-west-2.amazonaws.com/cloudformation/2020-06-10/dns.yaml) use `/health` endpoint as readiness endpoint on CoreDNS pods as following:

```yaml
readinessProbe:
  httpGet:
    path: /ready
    port: 8080
    scheme: HTTP
```

Amazon EKS should use `/ready` endpoint on the readiness probe.  CoreDNS supports `/ready` endpoint by [ready plugin](https://coredns.io/plugins/ready/).  It is available since CoreDNS v1.5.0.

The manifest provides by Amazon EKS should enable a ready plugin, and use it on the readiness probe.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Using `/health` endpoint on the readiness probe does not guarantee *the pod is ready*.  It can cause down-time on DNS service in the cluster, probably.

**Are you currently working around this issue?**

1. Enable a ready plugin on `configmap/coredns` by `kubectl edit`:

```yaml
data:
  Corefile: |
    .:53 {
        errors
        health
        ready	# <-- HERE
```

2. Replace `readinessProbe` by `kubectl edit` or `kubectl path` as the following manifest:

```yaml
readinessProbe:
  httpGet:
    path: /ready
    port: 8181
    scheme: HTTP
```

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by z0rc** [comment] 2023-01-22 21:12
In addition to `ready` plugin, please add `lameduck` option to `health` plugin. See official reference at https://github.com/coredns/deployment/blob/coredns-1.14.0/kubernetes/coredns.yaml.sed#L51-L54

**Comment by jaroslaw-bochniak** [comment] 2023-06-21 11:15
Using `/ready` endpoint is a good idea, just to clarify, according to the CoreDNS [documentation](https://coredns.io/plugins/ready/) 

> By enabling ready an HTTP endpoint on port 8181 will return 200 OK, when all plugins that are able to signal readiness have done so. If some are not ready yet the endpoint will return a 503 with the body containing the list of plugins that are not ready. Once a plugin has signaled it is ready it will not be queried again.

So once pod becomes ready (with all plugins), the endpoint will always return 200. This leaves detection of the unready/unhealthy pod to the `livenessProbe` which typically has a little bigger `failureThreshold`. If my understanding is correct, we are trading here a little bit of safety in cases when new pod starts but is not yet fully ready vs faster detection of potentially unhealthy pod. Unless we will configure both `readinessProbe` and the `livenessProbe` to the same thresholds and periods to both `/ready` and `/health` endpoints.

**Comment by sjastis** [comment] 2023-08-25 00:07
Added capability in release(s) starting with coreDNS v1.9.3-eksbuild.6 and v1.10.1-eksbuild.3

**Comment by jeff-french** [comment] 2023-08-25 15:39
@sjastis This change resulted in core-dns pods not being ready for extended period of time causing dns resolution failures on EKS v1.24. Solution was to rollback coredns addon to 1.9.3-eksbuild.5. Where is the appropriate place to report issues with this change?

**Comment by sjastis** [comment] 2023-08-25 18:52
Thanks for reporting this, Jeff. We are looking into this.

**Comment by oliviassss** [comment] 2023-08-25 20:02
@jeff-french, thanks for reporting this. Currently, the livenessProbe and readinessProbe configuration is
```
    Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:    http-get http://:8181/ready delay=0s timeout=1s period=10s #success=1 #failure=3
```
We may need to change the default config to avoid such issue. Would you be able to share more info to help us better understand the ideal configuration here?

**Comment by jeff-french** [comment] 2023-08-25 20:46
I don't have a way to reproduce this at the moment as it happened in a production cluster that was immediately remediated. 

Everything was working correctly prior to upgrading the coredns addon. The info I do have is this:

EKS version: 1.24
Provisioned with EKS Terraform module:

```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "19.15.3"

  cluster_name                   = "${local.name_prefix}-eks"
  cluster_version                = "1.24"
  cluster_endpoint_public_access = true

  ...

  enable_irsa = true

  cluster_addons = {
    vpc-cni = {
      most_recent              = true
      resolve_conflicts        = "OVERWRITE"
      before_compute           = true
      service_account_role_arn = module.vpc_cni_irsa.iam_role_arn
    }
    coredns = {
      amost_recent      = true
      resolve_conflicts = "OVERWRITE"
    }
    kube-proxy = {
      most_recent       = true
      resolve_conflicts = "OVERWRITE"
    }
    aws-ebs-csi-driver = {
      most_recent              = true
      resolve_conflicts        = "OVERWRITE"
      service_account_role_arn = module.ebs_csi_irsa.iam_role_arn
    }
  }

  ...
}
```

Terraform was executed that updated the coredns version:

```
addon_version : "v1.9.3-eksbuild.5" ~> "v1.9.3-eksbuild.6"
```


When I discovered the situation there were 2 coredns pods that had been up for 24 minutes but had not yet entered a ready state:

```
coredns-6dc8f974bb-84mx4              0/1     Running   0                  24m
coredns-6dc8f974bb-n4hfk              0/1     Running   0                  24m
```

I tailed the logs of one pod and found this:

```
kc logs -f coredns-6dc8f974bb-84mx4 -n kube-system
.:53
[INFO] plugin/reload: Running configuration SHA512 = 8a7d59126e7f114ab49c6d2613be93d8ef7d408af8ee61a710210843dc409f03133727e38f64469d9bb180f396c84ebf48a42bde3b3769730865ca9df5eb281c
CoreDNS-1.9.3
linux/amd64, go1.20.4, 5df0a51b
[INFO] Reloading
[INFO] plugin/health: Going into lameduck mode for 5s
[INFO] plugin/reload: Running configuration SHA512 = 45856c1f081233b2c4151cc298eaa14ad5fa461ea2de931873f385fe8464ffbf71a240508b3fe6d339cd4d7e4c354880db2fd5279e38efbb843d5f1c6334b721
[INFO] Reloading complete
```

That was the extent of the logging and no new messages were flowing.

At that point I rolled back the coredns addon version to `v1.9.3-eksbuild.5`

**Comment by oliviassss** [comment] 2023-08-28 17:56
@jeff-french, thanks for the details. I couldn't reproduce this error on my setup, but the port of readinessProbe was changed to `8181` as the default port of `/ready` plugin, would that be the cause of your issue?

**Comment by jeff-french** [comment] 2023-08-28 19:08
It's possible. I really don't know what the mechanism is for deploying / updating managed EKS addons behind the scenes. This is done either via the EKS console or (in my case) via the API (using Terraform). Once that process is initiated I have no visibility into what it actually does. Is it a helm chart? Is it a set of k8s manifests being applied? Is there anywhere for the public to gain some visibility into the process of addon updates?

**Comment by oliviassss** [comment] 2023-08-28 19:14
@jeff-french, currently we leverage the [eks docs](https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html) for eks managed coreDNS. we are working with our internal team to call out the latest changes on it.

**Comment by gmonne-universe** [comment] 2023-09-04 13:47
Updating the plugin through `eksctl` doesn't seem to apply the correct changes to the `ConfigMap` and `Deployment` that are described here: https://github.com/coredns/deployment/blob/coredns-1.14.0/kubernetes/coredns.yaml.sed#L51-L54

I fixed this issue by manually updating those files according to the source.

**Comment by oliviassss** [comment] 2023-09-04 15:40
@gmonne-universe, which eksctl command did you use? Since these two versions are not default version of the eks versions, if you're updating eks version it may not be using the latest coreDNS versions. You can update the addon version by `aws eks update-addon --addon-name coredns --addon-version XXX` to the specific versions of eks managed coredns

**Comment by iodeslykos** [comment] 2023-09-06 16:55
For those of you installing `>1.9.3.eksbuild.6` as an EKS add-on via Terraform and possibly other platforms:

Ensure that the `coredns` configmap in the `kube-system` namespace includes the `/ready` endpoint, otherwise the pods will hang indefinitely and never be marked ready. It may require a manual edit of the configmap via `kubectl edit` in order to get the pods' readiness check to pass.

It would look something like (truncated):

```yaml
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
```

The configmap does not appear to update automatically when deploying via Terraform, so in the resource block for the coredns `aws_eks_addon`, this is achieved by supplying the corefile as `configuration_values`.

**Comment by jvahldick** [comment] 2023-09-27 14:50
Thanks

Your advice helped me to fix my issues. In the case:
-> added manually the "ready" to the ConfigMap
-> edit the Deployment of the coredns, changing the port of readinessProbe to 8181

**Comment by sjastis** [comment] 2024-01-17 23:25
Closing this issue as the original request was addressed. Please let us know if you feel otherwise.

**Closed by sjastis** 2024-01-17 23:25 UTC
Labels: EKS, Proposed, EKS Networking
