### ISSUE TITLE
[eks] [request]: Support for Kubernetes v1.23

### ISSUE THREAD

**Issue by stevehipwell** [aws/containers-roadmap#1659] opened 2022-02-23 11:12 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Kubernetes v1.23 has been [released](https://kubernetes.io/blog/2021/12/07/kubernetes-1-23-release-announcement/) (at the beginning of December 2021) and we need to track the ability to create an EKS cluster using K8s v1.23. I'd really like to see this be a quicker turn around than for v1.22. I'd also like to see a rough guide of release windows in the [calendar](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar) with the understanding that this isn't a commitment.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Until EKS supports K8s v1.23 I can't have a managed control plane for K8s v1.23. The longer it takes EKS to support a K8s version the worse the user experience both from the perspective of new features and official support.

**Are you currently working around this issue?**
n/a

**Additional context**
n/a

**Attachments**
n/a

**Comment by mikestef9** [comment] 2022-02-23 16:43
Closing as duplicate of #1595

**Closed by mikestef9** 2022-02-23 16:43 UTC
Labels: Proposed

**Comment by mikestef9** [comment] 2022-02-23 16:49
Ya I searched too and didn't find it either. I think something weird is going on with GitHub search

**Comment by stevehipwell** [comment] 2022-02-23 16:50
> Ya I searched too and didn't find it either. I think something weird is going on with GitHub search

Phew, I thought I was going mad!!
