### ISSUE TITLE
[EKS] [request]: Create EKS VPC endpoint for node bootstrapping in private VPC

### ISSUE THREAD

**Issue by sjherrick** [aws/containers-roadmap#745] opened 2020-02-10 19:00 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Create a VPC endpoint for eks.REGION.amazonaws.com to allow nodes in private VPCs to join cluster.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I have a cluster in a private VPC that is isolated from the internet by design. It communicates with private resources via a Direct Connect.

When new nodes are deployed, the EC2 instance runs the bootstrap script **/etc/eks/bootstrap.sh**. Among other things, this runs the commands **aws eks wait cluster-active** and **aws eks describe-cluster**. These make calls to a public URL **https://eks.us-east-1.amazonaws.com/clusters/cluster-name**.

EKS can create new EC2 instances, but they will not join the cluster as nodes. 

Other services have VPC endpoints to allow communication to these endpoints, but not EKS. 

```
 cloud-init: Connect timeout on endpoint URL: "https://eks.us-east-1.amazonaws.com/clusters/<cluster-name>"
```
**Are you currently working around this issue?**
After making changes to our Node Group, I create temporary routes to internet gateways, SSH to the EC2s and execute the bootstrap script.

**Comment by RyPeck** [comment] 2020-02-17 15:22
Have you seen https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html

**Comment by mikestef9** [comment] 2020-02-17 16:47
Closing as a duplicate of #298. That ticket has some more info on how nodes can join the cluster in a completely private subnet without requiring a VPC endpoint for EKS

**Closed by mikestef9** 2020-02-17 16:47 UTC
Labels: Proposed
