### ISSUE TITLE
[EKS] [request]: Egress IP (SNAT) per Namespace

### ISSUE THREAD

**Issue by sarunaaa003** [aws/containers-roadmap#2181] opened 2023-10-18 17:06 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?
Enterprise customers traditionally protects shared backend services (ex.: databases, integration-bus and storage) using allow-list/block-list based on IP addresses. There is not a way to replicate this capability with Amazon EKS with VPC CNI plugin. 

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.
Every POD connecting externally will have a dedicated IP from Egress IP pool

**Are you currently working around this issue?**
How are you currently solving this problem?
The current workaround is to have a static SNAT IP address defined for specific EKS node groups, with NAT Gateways at VPC networking level, but this does not address the same use cases.

**Comment by mikestef9** [comment] 2023-10-18 17:15
Closing as duplicate of #1319

**Closed by mikestef9** 2023-10-18 17:15 UTC
Labels: Proposed
