### ISSUE TITLE
[ECS] [Service Discovery]: Service discovery is failing when you run the service on blue green deployment on ECS

### ISSUE THREAD

**Issue by GokulaAdabala** [aws/containers-roadmap#645] opened 2019-12-11 07:40 UTC
I have deployed my services on ECS with blue-green deployment & Service Discovery. This blue/green deployment was achieved using Code Deploy. when I do a new deployment the old task will run for 1 hour during that time new task only will get the traffic but not the old one. the problem here it is whenever I resolve the service discovery(dns) I still get the old task which won't get the traffic. Can you please resolve this issue to get the tasks which are getting traffic.  I hope i conveyed what I think. Please resolve this issue asap and also correct if am wrong.

**Comment by kkopachev** [comment] 2020-01-09 19:26
duplicate of #648

**Comment by coultn** [comment] 2020-01-10 23:45
Closing as duplicate

**Closed by coultn** 2020-01-10 23:45 UTC
Labels: ECS, Proposed
