### ISSUE TITLE
Early (Preview / Beta) access to new EKS version release

### ISSUE THREAD

**Issue by jboreddy** [aws/containers-roadmap#1974] opened 2023-03-10 02:08 UTC
ISV customers test compatibility with K8s versions on each EKS release. They have number of customers running workloads on EKS that are impacted by new release. Some of these customers take 4 - 8 weeks post-EKS release for their GA release. This depends on the magnitude of change which includes engineering work, QA, early LA release etc. The end customers of ISV will take another 13-20 weeks post ISV GA release. 
Enforcement of auto-upgrades by EKS for out-of-support versions is causing some challenges because of the above reason. So, providing early access to EKS beta versions would allow ISVs to ensure their latest releases are compatible with latest EKS versions, effectively extending compatibility windows for supported versions.

**Comment by mikestef9** [comment] 2023-03-10 04:46
Closing as duplicate of #544 which is similar request for early access to Kubernetes versions

**Closed by mikestef9** 2023-03-10 04:46 UTC
Labels: EKS, Duplicate / Merged
