### ISSUE TITLE
[EKS] [request]: Dynamic provisioning for EFS CSI driver

### ISSUE THREAD

**Issue by ckdarby** [aws/containers-roadmap#1031] opened 2020-08-12 18:42 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Dynamic provisioning support for the EFS CSI driver which @leakingtapan did an excellent job of [outlining](https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/6). The issue hasn't been tackled in over a year and this looks like a good collaboration between EKS and EFS team and probably should belong on the container roadmap because it is related specifically to AWS.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We're using [Airflow](https://airflow.apache.org/) which requires the DAG files to be shared across three pods (Scheduler, Worker and Web). We figured this would be an excellent use case for AWS EFS. We're avoiding using the older provisioner as it has been retired and would like to use the new EFS CSI driver for this functionality.

**Are you currently working around this issue?**
Yes, we're currently using terraform to create the EFS when we're creating the EKS cluster itself.

This causes a lot of headaches because our helm charts are unaware of the output from terraform without us providing the value.

**Comment by mikestef9** [comment] 2020-08-12 18:56
Closing as duplicate of #891. No timeline for this feature, but we are working with EFS team to get this prioritized.

**Closed by mikestef9** 2020-08-12 18:56 UTC
Labels: EKS, Proposed
