### ISSUE TITLE
[EKS] [request]: Optional creations of AWS-CNI, Kube-proxy to manage them in helm charts

### ISSUE THREAD

**Issue by mohsen0** [aws/containers-roadmap#934] opened 2020-06-07 22:07 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Currently, On the creation of an EKS cluster, Workloads like AWS CNI, Kube proxy, kube-dns are created automatically, Can we make that optional? So we can manage those workloads in helm or other tools. it will help us to use charts like aws-cni and be able to adjust different configurations.

https://github.com/aws/eks-charts/tree/master/stable

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
To be able to manage all the core Kubernetes services with tools like helm.
Sevices like, AWS CNI, kube-proxy, kube-dns
For example, 
- In order to enable the metrics endpoint of kube-proxy, currently, we have to patch the object manually. 

- In order to set make the AWS-CNI use RISA(IAM roles for service accounts ) to authenticate with IAM, we have to add an annotation to the service account. With the helm chart provided in aws/charts, that is very simple but in order to roll that out for the first time, some manual interventions are required.

**Are you currently working around this issue?**

- In order to use the aws-cni chart, (using helm 2.xx) we have to remove the old objects and deploy the chart to have aws-node resources.
- In order to enable metric enable of Kube-proxy, Kube objects need to be patch manually 

**Additional context**
https://github.com/aws/containers-roadmap/issues/657
https://github.com/aws/eks-charts/issues/156

**Comment by mikestef9** [comment] 2020-06-08 20:33
Hey @mohsen0, closing this as a duplicate of #923. The functionality you are asking for is coming as part of #252

**Closed by mikestef9** 2020-06-08 20:33 UTC
Labels: Proposed
