### ISSUE TITLE
[EKS] [request]: Add header based routing in ALB Ingress Controller

### ISSUE THREAD

**Issue by pcr132** [aws/containers-roadmap#494] opened 2019-09-23 14:57 UTC
**Tell us about your request**
What do you want us to build?
AWS ALB Ingress Controller for EKS

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Recent AWS ALB announcements introduced advanced routing rules which specifically allowed header based routing in ALB. Reference link below,

https://aws.amazon.com/blogs/aws/new-advanced-request-routing-for-aws-application-load-balancers/

AWS ALB Ingress controller does not have this feature currently and additional products are required to handle this routing today viz. nginx, app mesh or Istio.

**Are you currently working around this issue?**
Currently we are forced to use another product such as nginx to enable this routing. It will be nice to have this feature inbuilt in AWS ALB Ingress so only one product can handle it. To handle blue/green deployments in EKS we are in need of this feature. 

Please let me know if you need any additional details.

**Comment by astrived** [comment] 2020-05-05 22:33
The issue is fixed with Ingress controller release 1.1.5 https://github.com/kubernetes-sigs/aws-alb-ingress-controller/releases/tag/v1.1.5

**Closed by astrived** 2020-05-05 22:33 UTC
Labels: EKS, Proposed
