### ISSUE TITLE
New EKS Region : Brasil

### ISSUE THREAD

**Issue by reddamazon** [aws/containers-roadmap#75] opened 2018-12-19 16:35 UTC
EKS in the Brasil region would be useful.

**Comment by brunopadz** [comment] 2019-01-08 16:03
Yeah! It'd be great :)

**Comment by tabern** [comment] 2019-01-16 18:04
Duplicate of #112

**Closed by tabern** 2019-01-16 18:04 UTC
Labels: EKS, Proposed

**Comment by tabern** [comment] 2019-10-17 23:06
Happy to announce that EKS is now generally available in the AWS São Paulo (sa-east-1) region!

* [What's new post](https://aws.amazon.com/about-aws/whats-new/2019/10/amazon-eks-generally-available-in-sao-paulo-region/)
* [EKS documentation & AMIs](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html)
* **eksctl** - creating clusters in sa-east-1 is supported with eksctl starting with [version 0.7.0](https://github.com/weaveworks/eksctl/releases)
