### ISSUE TITLE
[EKS] [request]: EBS volume encryption for managed node groups

### ISSUE THREAD

**Issue by matthack** [aws/containers-roadmap#1016] opened 2020-08-06 00:21 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Support for EBS volume encryption for EKS's managed node groups.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Excited to use managed node groups with EKS, however we have regulatory compliance which requires our worker node root volumes to be encrypted, thus preventing our consumption.

**Are you currently working around this issue?**
Creating our own launch configs with EBS root volume encryption enabled and autoscaling groups.

**Additional context**
The ability to use the included KMS key from AWS or a customer managed key would be nice.

**Attachments**

**Comment by mikestef9** [comment] 2020-08-06 02:39
Closing as a duplicate of #665. This will be possible very soon #585

**Closed by mikestef9** 2020-08-06 02:39 UTC
Labels: Proposed
