### ISSUE TITLE
[EKS] [cost-by-namespace]: Track EKS Costs Grouped by Namespaces

### ISSUE THREAD

**Issue by gluckzhang** [aws/containers-roadmap#2018] opened 2023-05-02 11:57 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I would like to fetch EKS cost information grouped by namespaces via Cost Explorer APIs (such as `GetCostAndUsage`).

**Which service(s) is this request for?**
EKS + CostExplorer

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
In some of our EKS clusters, different development teams share the same cluster but use different namespaces for their services. That would be nice to see each team's cost on the EKS cluster via cost explorer APIs.

**Are you currently working around this issue?**
I know KubeCost/OpenCost provides such a feature (cost by namespace) but this means we have to write extra code to query OpenCost's API and update our internal cost-management tools based on the responses. We have already implemented the queries from AWS cost explorer to track each EKS cluster's cost. If the cost explorer can directly respond with cost information by namespace, that would be very convenient.

**Comment by luarx** [comment] 2023-05-09 13:54
Super useful! If AWS can provide the cost of EKS clusters by namespace, deployment...etc. as Kubecost does, this definitely will help to know what it is the cost of the different cluster pieces

**Comment by andrewhharmon** [comment] 2024-02-23 18:51
Something like what was done for batch would be really useful. https://aws.amazon.com/about-aws/whats-new/2023/04/aws-split-cost-allocation-data-amazon-ecs-batch/

**Comment by mikestef9** [comment] 2024-04-11 22:15
Closing as duplicate of #1021 which is now marked as coming soon

**Closed by mikestef9** 2024-04-11 22:15 UTC
Labels: EKS, Proposed
