### ISSUE TITLE
[EKS] [request]: Supporting AWS Secrets Manager in Secrets Store CSI Driver

### ISSUE THREAD

**Issue by danmx** [aws/containers-roadmap#895] opened 2020-05-13 09:29 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

There is an initiative (Azure led?) [Secrets Store CSI Driver](https://github.com/kubernetes-sigs/secrets-store-csi-driver) to mount secrets as volumes. It would be very useful to use it with AWS Secrets Manager.

**Which service(s) is this request for?**

EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

This would remove the need for CRDs for Secrets management (e.g. [Sealed Secrets](https://github.com/bitnami-labs/sealed-secrets) or [External Secrets](https://github.com/godaddy/kubernetes-external-secrets)) or pushing secrets to etcd.

**Are you currently working around this issue?**

Using custom in-house solution.

**Additional context**

If that would work with Secrets Manager and was integrated into EKS natively you'd be solving major problem for all of your customers and lowering the bar for Secrets Manager adoption 😉 

**Attachments**

[Secrets Store CSI Driver - Criteria for Supported Providers](https://github.com/kubernetes-sigs/secrets-store-csi-driver#criteria-for-supported-providers)

**Comment by smitthakkar96** [comment] 2020-05-23 10:28
I am thinking of working on this up if anyone wants to collaborate and conquer shoot me an email on smitthakkar96@gmail.com

**Comment by mikestef9** [comment] 2021-04-21 04:28
Closing as a duplicate of #168. And just moved #168 to coming soon.

**Closed by mikestef9** 2021-04-21 04:28 UTC
Labels: EKS, Proposed
