### ISSUE TITLE
[Fargate] [request]: Specify the Fargate compute architecture for AWS Batch jobs

### ISSUE THREAD

**Issue by rleighton** [aws/containers-roadmap#1731] opened 2022-04-30 19:24 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

Since AWS [announced](https://aws.amazon.com/about-aws/whats-new/2021/11/aws-fargate-amazon-ecs-aws-graviton2-processors/) Fargate support for ARM64 architecture I would like for Batch jobs running on Fargate to use ARM64. For ECS tasks, we can specify this in runtimePlatform in the [task definition](https://docs.aws.amazon.com/AmazonECS/latest/userguide/ecs-arm64.html).

See: https://repost.aws/questions/QUkKTvomuXRMaNsQ_f0Piunw/arm-64-support-for-batch-jobs-on-aws-fargate

**Which service(s) is this request for?**
Fargate (from Batch)

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
ARM64 not supported in JobDescription form Batch

**Are you currently working around this issue?**
How are you currently solving this problem?

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by tlinhart** [comment] 2022-10-21 06:08
Duplicate of https://github.com/aws/containers-roadmap/issues/1652.

**Comment by ollypom** [comment] 2023-07-18 08:41
AWS Batch Jobs on AWS Fargate now supports Linux arm64 and Windows x86. 

Whats new post: https://aws.amazon.com/about-aws/whats-new/2023/07/aws-batch-fargate-linux-arm64-windows-x86-containers-cli-sdk/

**Closed by ollypom** 2023-07-18 08:41 UTC
Labels: Proposed
