### ISSUE TITLE
[EKS] EC2 instance naming: Default naming for EC2 instances created by an EKS cluster inherited from cluster name

### ISSUE THREAD

**Issue by kevinctz** [aws/containers-roadmap#1663] opened 2022-02-25 09:03 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Add a default Name tag to EKS-created EC2 instances, with some reference to EKS cluster responsible for creation, such as including the EKS cluster name.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Including a default Name tag for EC2 instances created by an EKS cluster will make the EC2 instance list easier to interpret and more useful when several EC2 instances are present from different EKS clusters, making instances' clusters immediately identifiable.

**Are you currently working around this issue?**
Currently, this can be achieved by manually modifying the Launch Template created automatically by EKS.

**Comment by mikestef9** [comment] 2022-02-25 16:49
Closing as duplicate of #781

**Closed by mikestef9** 2022-02-25 16:49 UTC
Labels: EKS, Proposed, EKS Managed Nodes, Duplicate / Merged
