### ISSUE TITLE
[EKS] API Options for Deprecation/Availability versions

### ISSUE THREAD

**Issue by ncole** [aws/containers-roadmap#989] opened 2020-07-17 18:24 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I would like a published API to surface that I need to upgrade my cluster.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
As of this writing, the available versions in EKS are 1.15, 1.16, 1.17.  However, using the EKS api, 1.14 clusters are still available, which is working fine.

What I would like to have is an API that allows me, for a cluster, to know if the version is Deprecated.  It is possible to have a deprecated version but yet still be valid. Basically, I would like the trigger for the following screenshot:

![Screen Shot 2020-07-17 at 2 14 34 PM](https://user-images.githubusercontent.com/2465245/87818180-2bfdd280-c838-11ea-8253-cce70b208f9e.png)

In addition, I would like an API call to know the available versions to upgrade to (and dependencies as outlined in the Upgrade Instructions:  https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html).  Or at least, the API to get this information (dialog box slightly truncated):

![Screen Shot 2020-07-17 at 2 18 50 PM](https://user-images.githubusercontent.com/2465245/87818438-8b5be280-c838-11ea-9dbf-6862b2b5e5dc.png)

Thank you

**Comment by mikestef9** [comment] 2024-12-20 22:21
Closing as duplicate of #982

**Closed by mikestef9** 2024-12-20 22:21 UTC
Labels: EKS, Proposed
