### ISSUE TITLE
[EKS] [request]: Adding subnets from previously unused AZs

### ISSUE THREAD

**Issue by blanchardma** [aws/containers-roadmap#2330] opened 2024-04-18 15:00 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Add subnets of Availability Zones (AZs) to the EKS control plane that were not originally provided when the cluster was created. 
**OR IN OTHER WORDS:** We need to expand our EKS to include subnets from additional Availability Zones (AZs) that weren't originally included when the cluster was set up. (For a better context read also the limitation at the end.)

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
The ability to extend the number of Availability Zones (AZ) and corresponding subnets for the EKS control plane, so that elastic network interfaces (ENIs) of the EKS control plane can also be created in the customer VPC.
This is difficult because it is not supported by the AWS service and you have to recreate the entire EKS control plane. 

**Are you currently working around this issue?**
Not really, you can either recreate the EKS control plane or leave it in the previous subnets and AZs.

**Additional context**
The limitation is currently described as follows in the AWS documentation: 
_"All subnets that you add must be in the same set of AZs as originally provided when you created the cluster."_
https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html#network-requirements-vpc

**Comment by sid-jar** [comment] 2024-06-19 10:36
Had there been any update or any proposed date of action onto this ? @blanchardma

**Comment by chotiwat** [comment] 2024-11-13 00:52
We might want to consolidate this with #2258

**Comment by mikestef9** [comment] 2024-11-13 04:47
Closing as duplicate of #2258

**Closed by mikestef9** 2024-11-13 04:47 UTC
Labels: EKS, Proposed, Duplicate / Merged

**Comment by chotiwat** [comment] 2024-11-13 23:52
Thanks, @mikestef9! It looks like #2258 isn't part of the containers-roadmap project. Could you also make sure it picks up the `Researching` status from this PR in the project?
![image](https://github.com/user-attachments/assets/4a7f9acb-1e19-4be1-9865-5b762968a3b9)

**Comment by blanchardma** [comment] 2024-11-18 09:52
@mikestef9 as already mentioned in the last comment, if you close this story as a duplicate, then #2258 should be on the roadmap with the status `researching`. Now #2258 is still not on the roadmap and this issue here is `closed`.
