### ISSUE TITLE
[ECS/Fargate] [request]: Allow archiving/persistence of `describe-tasks` data for stopped tasks

### ISSUE THREAD

**Issue by zbintliff** [aws/containers-roadmap#677] opened 2020-01-06 20:48 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
When diving into issues on _why_ tasks exited we find that the stopped tasks are purged fairly quickly from both the service and the UI.
Being able to have the task state around longer would help us know why certian containers stopped (healthcheck, essential container die, OOM, etc). This also lets us easily know which instances a task was running on without having to dive into ECS Agent logs.

Today it seems after ~1 hour they are purged. This isn't ideal when resolving issues and trying to go back later to investigate root cause.

**Which service(s) is this request for?**
Fargate, ECS

**Are you currently working around this issue?**
ECS Agent logs

**Comment by sparrc** [comment] 2023-04-14 21:03
closing as a dupe of https://github.com/aws/containers-roadmap/issues/1246

**Closed by sparrc** 2023-04-14 21:03 UTC
Labels: ECS, Proposed

**Comment by staceywhou** [comment] 2025-10-02 21:55
Amazon ECS now supports one-click event capture and event history querying in the AWS Management Console ([what's new](https://aws.amazon.com/about-aws/whats-new/2025/10/amazon-ecs-one-click-event-capture-history-querying-console/)) which enables you to set up EventBridge and retain data beyond 1 hr directly in the ECS console.
