### ISSUE TITLE
[ECS] [request]: pin the ecs-agent version rather then use amazon/amazon-ecs-agent:latest in the Amazon ECS-optimized Amazon Linux's

### ISSUE THREAD

**Issue by danbf** [aws/containers-roadmap#1401] opened 2021-06-11 15:39 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
The Amazon ECS-optimized Amazon Linux 2 AMI does not pin ecs-agent versions as implied in https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-versions.html.  Can we pin them so we don't have unexpected issues?

**Which service(s) is this request for?**
ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently the ecs-agent that is loaded in the Amazon ECS-optimized Amazon Linux 2 AMI that we run load `amazon/amazon-ecs-agent:latest` rather then a pinned version of the ecs-agent as implied by https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-versions.html .  

For example we have an ecs node built off `ami-09edd32d9b0990d49`/`amzn2-ami-ecs-hvm-2.0.20200402-x86_64-ebs`. the chart on https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-versions.html says it should have ecs-agent version `1.39.0`.  Looking at the AWS console, it shows the instance running `1.44.3` which was `latest` when this the AMI we are running was customized by packer and stored. https://hub.docker.com/layers/amazon/amazon-ecs-agent/v1.44.3/images/sha256-07a4494fb67b8dbc95e80859d4d0230ea90a30d92c148dd5d0b232d20f0024e0?context=explore .  

```
docker ps | grep [a]gent
21cac436573b        amazon/amazon-ecs-agent:latest   "/agent"            4 minutes ago       Up 4 minutes (healthy)                       ecs-agent
```

**Are you currently working around this issue?**
We are not but are concerned since a recently the `latest` version of `aws-for-fluent-bit` introduced both a seg fault and memory leak from it's upstreams. https://github.com/aws/aws-for-fluent-bit/issues/184 . We are concerned about the same thing happening to the ecs-agent  and as a result our fleet having an issue since we are not pinned. Especially with issues like https://github.com/aws/amazon-ecs-agent/issues/2865

**Comment by danbf** [comment] 2021-06-11 21:13
i suspect the issue is that https://github.com/aws/amazon-ecs-init/blob/master/ecs-init/config/common.go#L32-L33 `AgentImageName` is not specified in when the AMI installs the `amazon-ecs-init` rpm.

**Comment by angelcar** [comment] 2021-06-14 19:17
Closing as this is a dupe of https://github.com/aws/amazon-ecs-agent/issues/2896.

**Closed by angelcar** 2021-06-14 19:17 UTC
Labels: Proposed
