### ISSUE TITLE
[EKS] Cloudwatch Logs for Containers

### ISSUE THREAD

**Issue by vincentheet** [aws/containers-roadmap#66] opened 2018-12-14 19:31 UTC
**Tell us about your request**
I would like to have a feature where I can enable a "Send all container logs to CloudWatch Logs"  flag. And then forget about managing the tooling to push the logs to CloudWatch Logs.

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I would like to have an aggregated, searchable, managed logging service for the logs of my Kubernetes Pod's. So for example I can search for a specific error trough all my K8S Pod logs. Currently this is possible to realize with a Helm chart: https://github.com/helm/charts/tree/master/incubator/fluentd-cloudwatch 
But I would rather have a fully manged experience where I don't have to worry about Helm or IAM for example. 

**Are you currently working around this issue?**
Not yet but I would probably start using the fluentd-cloudwatch Helm chart.

**Additional context**
In comparison Google Kubernetes Engine has a similar feature. Check the box marked "Enable Stackdriver Logging service" and your logs start flowing in to their hosted logging service. This request differs from https://github.com/aws/containers-roadmap/issues/26 where the control plane logs are requested, not the container logs.

**Comment by badping** [comment] 2019-01-15 14:47
Feedback: Currently there is no "How-To" which explains the steps sending pod logfiles into the cloudwatch service. There is only a "How-To" sending Cloud-Watch logs to Elastic-Search.
I think this missing "How-To" could be a good starting point.
However i support the idea of even a better integration with less effort to configure.

**Comment by mfacenet** [comment] 2019-01-17 00:55
If nothing else, it would at least be beneficial if there were documentation on how to deploy fluentd to push all container logs to cloudwatch logs.  Although theoretically an option fluentd daemonset and updated iam roles with cloudwatch permissions in the samples would be preferable.

**Comment by runningman84** [comment] 2019-01-17 06:54
@mfacenet check this out:
https://eksworkshop.com/logging

**Comment by BrianChristie** [comment] 2019-02-20 12:15
Two requests:
### CloudWatch Log Groups

We would like to see this implemented in a way that can automatically create a CloudWatch Logs LogGroup per Kubernetes Deployment.

The [FluentD-CloudWatch](https://github.com/fluent-plugins-nursery/fluent-plugin-cloudwatch-logs) plugin sends all logs to a single LogGroup and each Pod is represented as a Log Stream within that group. This is a poor experience when attempting to find Pod Logs.

### Log Contents
The log agent used should be able to properly handle nested escaped JSON. 
When log lines are emitted from a Container as JSON, the Docker JSONFile log driver adds escaping. Especially with [CloudWatch Logs Insights](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AnalyzingLogData.html) it's important that these are properly parsed back out to valid JSON so they can be searched and aggregated.


As vincentheet noted, the experience on other managed providers is extremely streamlined, it will be great to have something similar available on EKS.

**Comment by outcoldman** [comment] 2019-03-13 19:55
For folks, who is still waiting. 

We (Outcold Solutions) just released a support of collectord (container-native log forwarding tool) for CloudWatch Logs and S3/Glue https://collectord.io/blog/2019-03-13-aws-centralized-logging-for-kubernetes/

It is very easy to install, allows you to keep the logs in long term on S3 (compressed, formatted, partitioned with Glue/Hive compatible format) and analyze them with Athena and QuickSight. And at the same time keep the logs in CloudWatch Logs as well. 

But just to be clear, we aren't a part of AWS, we aren't open source company. Collectord is a proprietary software, that we distribute, including with AWS Marketplace. We charge the minimum possible amount for the licensing. At the bottom of the blog post I shared you can find a calculator, that can estimate the monthly price for using AWS Services and our license as well.

**Comment by mattcow** [comment] 2019-05-23 14:17
This is the only related issue I saw for sending EKS container logs to Cloudwatch, so it seems worth mentioning these docs: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-logs.html

Container Insights for EKS seems to be in developer preview so maybe this issue should move under that column?

**Comment by tabern** [comment] 2019-06-17 03:42
@vincentheet would you consider [CloudWatch Container Insights](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-reference-performance-entries.html) as a solution to this request? If not, what could we add to fulfill the need?

**Comment by jacobwgillespie** [comment] 2019-06-17 06:41
@tabern does CloudWatch Container Insights support shipping the raw container logs to CloudWatch?

**Comment by vincentheet** [comment] 2019-06-17 08:00
> @vincentheet would you consider [CloudWatch Container Insights](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-reference-performance-entries.html) as a solution to this request? If not, what could we add to fulfill the need?

Although this might work it's not what I intended with my feature request. I currently have FluentD running in my EKS clusters but it involves some manual intervention and maintenance.

> But I would rather have a fully managed experience where I don't have to worry about Helm or IAM for example.

> In comparison Google Kubernetes Engine has a similar feature. Check the box marked 'Enable Stackdriver Logging service' and your logs start flowing in to their hosted logging service. 

Unfortunately it seems like it's nowhere near the simplicity I would like as I look at the documentation: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-logs.html

**Comment by PettitWesley** [comment] 2019-07-10 06:32
You can now use Fluent Bit to send logs from K8s to CloudWatch, see the following:

- Tutorial: https://aws.amazon.com/blogs/opensource/centralized-container-logging-fluent-bit/
- Documentation: https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit

**Comment by evmin** [comment] 2020-02-16 08:41
Any updates on the native solution? 
Or the fluent bit is the recommended way? 
How would it work with FarGate, where DaemonSets are not available?

**Comment by GaramNick** [comment] 2020-04-24 10:26
Personally, I've found the [Quick Start Setup](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-EKS-quickstart.html) very user friendly. One line to setup and send logging & monitoring data to CloudWatch.

**Comment by uma66** [comment] 2020-04-28 12:54
>Personally, I've found the Quick Start Setup very user friendly. One line to setup and send logging & monitoring data to CloudWatch.

It supports EC2 pod, but not Fargate pod.

I hope that this [Quick Start Setup](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-EKS-quickstart.html) will allow not only EC2 but also Fargate logs to be aggregated into container insight.

**Comment by bwagnertrc** [comment] 2020-07-08 15:58
> The log agent used should be able to properly handle nested escaped JSON.
> When log lines are emitted from a Container as JSON, the Docker JSONFile log driver adds escaping. Especially with [CloudWatch Logs Insights](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AnalyzingLogData.html) it's important that these are properly parsed back out to valid JSON so they can be searched and aggregated.

You can achieve that by adding a parser to the fluentd configuration. This allows you to query nested JSON fields from your log output in CloudWatch Insights.

```
    <filter **>
        @type parser
        format json
        key_name log
        reserve_time true
        reserve_data true
        emit_invalid_record_to_error false
        hash_value_field parsed_log
    </filter>
```

See https://medium.com/@k5trismegistus/use-cloudwatch-to-monitor-eks-cluster-and-gather-logs-from-rails-app-on-kubernetes-d86f4d9439f7

**Comment by NeckBeardPrince** [comment] 2020-08-12 20:47
Unfortunately Container Insights is not available in GovCloud.

**Comment by pallabganai** [comment] 2020-11-25 10:31
Is this issue going to cover Fargate as well?

At the moment the [solution](https://aws.amazon.com/blogs/containers/how-to-capture-application-logs-when-using-amazon-eks-on-aws-fargate/) is to use logrotate and fluentd for each application pod. This increases the cost due to these additional logging related containers. For a small application container, the logging setup costs more than the application container. Is there any better solution available?

**Comment by mreferre** [comment] 2020-11-25 11:57
@pallabganai [this](https://github.com/aws/containers-roadmap/issues/701) is what we are working on for Fargate. The intention is to hide the sidecar ("hidecar") so that you don't have to deal with it.

**Comment by chainhead** [comment] 2020-12-08 18:11
`hidecar` - learnt something new today!

**Comment by koslib** [comment] 2020-12-28 20:47
Seems like the native Fargate logging solution [is out](https://docs.aws.amazon.com/eks/latest/userguide/fargate-logging.html) since the beginning of the month. Really a big deal as this was a huge con in terms of switching more services of ours to Fargate!

**Comment by visit1985** [comment] 2021-01-25 13:11
The Fargate logging solution released at the re:Invent 2020 creates CloudWatch log entries in the form of
`{"log": "2021-01-25T12:22:29.783415501Z stdout F here is your message"}`.

I don't think it was a good idea to put timestamp, output-stream and log-level in one string with the escaped log message.
Fixing this via configuration is currently not possible because of #1203.

Due to the same issue, we cannot parse nested JSON messages for now, which makes use of CloudWatch Insights impossible.

**Comment by visit1985** [comment] 2021-01-27 17:00
Meanwhile #1203 is fixed for clusters created as of last week.
We can parse nested JSON via (see [comment](https://github.com/aws/containers-roadmap/issues/1203#issuecomment-768415703)).

**Comment by mikestef9** [comment] 2021-01-27 17:11
@visit1985 would say you the latest fix from #1203 unblocks you from using Fargate logging solution? Separately, we are working on #1197

**Comment by mikestef9** [comment] 2021-01-27 17:17
Including this link as most of what is requested in the issue is now available

https://aws.amazon.com/blogs/containers/fluent-bit-integration-in-cloudwatch-container-insights-for-eks/

I'll leave this open for now, as we plan to add container insights to EKS add-ons, which will complete the fully managed experience

**Comment by Guillaume-Mayer** [comment] 2021-06-19 02:27
Hi there.
I have a similar case I think, containers in EKS logging in full Json but EKS default config show them as plain string in CloudWatch ("log" field).
Does someone know the correct way to configure FluentD to support both Json and plain text log?
I'm trying to convince my colleagues that Json is a good way to structure logs, but CloudWatch not recognizing it as such make it difficult.
It works out of the box in GCP so I'm pretty confident it's possible too with CloudWatch.
Take care
Guillaume

**Comment by PettitWesley** [comment] 2021-06-20 00:52
@Guillaume-Mayer Parsing json nested json inside the log key is a very common case, in fact its the most common case possibly. 

Fluent Bit is more efficient than Fluentd and is officially supported by AWS. The kubernetes filter in fluent bit can automatically parse the log key json and turn into top level keys, you can also set the option `Keep_Log` off: https://docs.fluentbit.io/manual/pipeline/filters/kubernetes

https://aws.amazon.com/blogs/containers/kubernetes-logging-powered-by-aws-for-fluent-bit/

Check out that tutorial and try it out. Fluent Bit also has parsers for json: https://docs.fluentbit.io/manual/pipeline/parsers/json

Spend some time playing with it, what you're asking for is a very common case that most tutorials should cover.

**Comment by kstevensonnv** [comment] 2024-01-12 13:55
@mikestef9 is this complete with the addition of the Amazon CloudWatch Observability agent addon?

**Comment by mikestef9** [comment] 2024-01-12 16:57
Ya I think we can finally close this one :)

https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-cloudwatch-container-insights-enhanced-observability-eks/

**Closed by mikestef9** 2024-01-12 16:57 UTC
Labels: EKS, Proposed, FluentBit

**Comment by visit1985** [comment] 2024-01-31 08:15
> Container Insights with enhanced observability for Amazon EKS is not supported on Fargate.

Please be aware, that we are still left with the fargate-logging config from 2021.
