### ISSUE TITLE
[EKS] [Request]: Graduate IAMIdentityMapping to general availability

### ISSUE THREAD

**Issue by sftim** [aws/containers-roadmap#1799] opened 2022-08-05 09:58 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Graduate `IAMIdentityMapping` to general availability

**Which service(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Declaratively define rules for mapping IAM principals to Kubernetes users and groups, using the Kubernetes API. This API is alpha so I'm wary to recommend it to customers.

**Are you currently working around this issue?**
Managing the `aws-auth` ConfigMap instead. This is a single point of co-ordination; it would be nice to set up EKS to also support IAMIdentityMappings.

**Additional context**
Example manifest for an `IAMIdentityMapping`:

https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/deploy/example-iamidentitymapping.yaml

**Comment by blowfishpro** [comment] 2023-05-10 19:53
Possibly related/equivalent to #550 ?

**Comment by mikestef9** [comment] 2024-01-29 19:22
Closing as duplicate of #550

**Closed by mikestef9** 2024-01-29 19:22 UTC
Labels: EKS, Proposed
